#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_NAME="MadModem"
VERSION="$(cat "$ROOT_DIR/MADMODEM_VERSION.txt" 2>/dev/null || echo dev)"
OUT_DIR="${MADMODEM_PACKAGE_OUT_DIR:-$ROOT_DIR/dist/packages}"
BUILD_LEGACY="${MADMODEM_WINDOWS_BUILD_LEGACY:-on}"
BUILD_AVX2="${MADMODEM_WINDOWS_BUILD_AVX2:-on}"
MXE_ROOT="${MXE_ROOT:-/usr/lib/mxe}"
MXE_TARGET="${MXE_TARGET:-x86_64-w64-mingw32.static}"
MXE_BIN="$MXE_ROOT/usr/bin"
OBJDUMP="${OBJDUMP:-$MXE_BIN/${MXE_TARGET}-objdump}"
STRIP="${STRIP:-$MXE_BIN/${MXE_TARGET}-strip}"

case "$(uname -s)" in
    Linux*) ;;
    *) echo "ERROR: MXE Windows packaging must run on Linux." >&2; exit 1 ;;
esac

mkdir -p "$OUT_DIR"

copy_common_payload() {
    local package_dir="$1"
    mkdir -p "$package_dir"

    for f in README.md RELEASE_NOTES.md CHANGELOG.md LICENSE.md COPYING AUTHORS.md THIRD_PARTY_NOTICES.md TRANSLATION_AUDIT.md cty.csv; do
        [[ -f "$ROOT_DIR/$f" ]] && cp -f "$ROOT_DIR/$f" "$package_dir/"
    done


    if [[ -d "$ROOT_DIR/docs/help" ]]; then
        mkdir -p "$package_dir/help"
        cp -f "$ROOT_DIR/docs/help"/*.css "$package_dir/help/" 2>/dev/null || true
        cp -f "$ROOT_DIR/docs/help"/*.qhp "$package_dir/help/" 2>/dev/null || true
        cp -f "$ROOT_DIR/docs/help"/*.qhcp "$package_dir/help/" 2>/dev/null || true
        for lang_dir in "$ROOT_DIR/docs/help"/{en,it,fr,de,no,cs}; do
            if [[ -d "$lang_dir" ]]; then
                mkdir -p "$package_dir/help/$(basename "$lang_dir")"
                cp -f "$lang_dir"/*.html "$package_dir/help/$(basename "$lang_dir")/" 2>/dev/null || true
            fi
        done
    fi
}

verify_static_exe() {
    local exe="$1"
    if [[ ! -x "$OBJDUMP" ]]; then
        echo "WARNING: objdump not found; cannot verify Windows DLL imports: $OBJDUMP" >&2
        return 0
    fi
    local imports
    imports="$($OBJDUMP -p "$exe" 2>/dev/null | sed -n 's/^\tDLL Name: //p' | sort -u || true)"
    printf '==> DLL imports for %s:\n%s\n' "$(basename "$exe")" "$imports"

    local forbidden='^(Qt5|Qt6|libgcc|libstdc\+\+|libwinpthread|libgomp|libhamlib|libicu|libpcre|libzstd|libpng|libharfbuzz|libdouble-conversion|libmd4c|zlib|libssl|libcrypto)'
    if printf '%s\n' "$imports" | grep -Eiq "$forbidden"; then
        echo "ERROR: MXE static package still imports non-system runtime DLLs:" >&2
        printf '%s\n' "$imports" | grep -Ei "$forbidden" >&2 || true
        exit 1
    fi
}

package_variant() {
    local variant="$1"
    local label="$2"
    local build_dir="$ROOT_DIR/build-windows-mxe-$variant"
    local exe_path="$build_dir/$APP_NAME.exe"
    local package_name="$APP_NAME-$VERSION-Windows-x86_64-$label-static"
    local package_dir="$OUT_DIR/$package_name"
    local zip_path="$OUT_DIR/$package_name.zip"

    if [[ ! -f "$exe_path" ]]; then
        echo "ERROR: executable not found for $variant: $exe_path" >&2
        exit 1
    fi

    rm -rf "$package_dir" "$zip_path"
    mkdir -p "$package_dir"
    cp -f "$exe_path" "$package_dir/$APP_NAME.exe"
    [[ -x "$STRIP" ]] && "$STRIP" "$package_dir/$APP_NAME.exe" || true

    copy_common_payload "$package_dir"

    cat > "$package_dir/RUN_WINDOWS.txt" <<TXT
MadModem Windows MXE static package
===================================

Run:
  MadModem.exe

Version: $VERSION
Variant: $label
Toolchain: MXE $MXE_TARGET static
Generated by: scripts/package_windows_mxe.sh

This package is built on GitHub using MXE static Qt/MinGW. It should not require
Qt, MinGW, MSYS2, ICU, PCRE, zstd, libgomp or Hamlib DLLs beside the EXE.
It is unsigned; Windows SmartScreen may warn the first time.
TXT

    cp -f "$package_dir/RUN_WINDOWS.txt" "$package_dir/BUILD_INFO.txt"

    verify_static_exe "$package_dir/$APP_NAME.exe"

    if find "$package_dir" -maxdepth 1 -iname '*.dll' -print | grep -q .; then
        echo "ERROR: MXE static package unexpectedly contains DLL files:" >&2
        find "$package_dir" -maxdepth 1 -iname '*.dll' -print >&2
        exit 1
    fi

    (cd "$OUT_DIR" && zip -rq "$zip_path" "$package_name")
    printf 'Windows MXE static package complete: %s\n' "$zip_path"
}

if [[ "$BUILD_LEGACY" != "off" ]]; then
    package_variant legacy legacy
fi
if [[ "$BUILD_AVX2" != "off" ]]; then
    package_variant avx2 avx2
fi
