"""Curated translations added for the MadModem 0.5.78 UI consolidation."""

# Stable runtime key -> language -> translated value.
KEYS = {
    "text.this_settings_page_will_be_loaded_when_selected": {
        "it": "Questa pagina delle Impostazioni verrà caricata quando viene selezionata.",
        "fr": "Cette page des réglages sera chargée lorsqu’elle sera sélectionnée.",
        "de": "Diese Einstellungsseite wird beim Auswählen geladen.",
        "no": "Denne innstillingssiden lastes når den velges.",
        "cs": "Tato stránka nastavení se načte po výběru.",
    },
    "text.connection_state_for_this_rotator_profile": {
        "it": "Stato della connessione per questo profilo rotore.",
        "fr": "État de la connexion pour ce profil de rotateur.",
        "de": "Verbindungsstatus für dieses Rotorprofil.",
        "no": "Tilkoblingsstatus for denne rotorprofilen.",
        "cs": "Stav připojení tohoto profilu rotátoru.",
    },
    "text.connect_or_disconnect_this_rotator_profile_immediately_without_leaving_settings": {
        "it": "Connetti o disconnetti subito questo profilo rotore senza uscire dalle Impostazioni.",
        "fr": "Connecter ou déconnecter immédiatement ce profil de rotateur sans quitter les réglages.",
        "de": "Dieses Rotorprofil sofort verbinden oder trennen, ohne die Einstellungen zu verlassen.",
        "no": "Koble denne rotorprofilen til eller fra uten å lukke innstillingene.",
        "cs": "Okamžitě připojit nebo odpojit tento profil rotátoru bez opuštění nastavení.",
    },
    "text.use_a_dedicated_serial_port_such_as_dev_ttyusb1_dev_cu_usbserial_or_com5_or_a_dedicated_ro": {
        "it": "Usa una porta seriale dedicata, ad esempio /dev/ttyUSB1, /dev/cu.usbserial o COM5, oppure un endpoint rotctld dedicato come rotctld:localhost:4533.",
        "fr": "Utilisez un port série dédié, par exemple /dev/ttyUSB1, /dev/cu.usbserial ou COM5, ou un point d’accès rotctld dédié tel que rotctld:localhost:4533.",
        "de": "Einen eigenen seriellen Port wie /dev/ttyUSB1, /dev/cu.usbserial oder COM5 oder einen eigenen rotctld-Endpunkt wie rotctld:localhost:4533 verwenden.",
        "no": "Bruk en egen serieport, for eksempel /dev/ttyUSB1, /dev/cu.usbserial eller COM5, eller et eget rotctld-endepunkt som rotctld:localhost:4533.",
        "cs": "Použijte vyhrazený sériový port, například /dev/ttyUSB1, /dev/cu.usbserial nebo COM5, případně vyhrazený endpoint rotctld, například rotctld:localhost:4533.",
    },
    "text.connecting": {"it": "Connessione...", "fr": "Connexion...", "de": "Verbindung wird hergestellt...", "no": "Kobler til...", "cs": "Připojování..."},
    "text.disconnecting": {"it": "Disconnessione...", "fr": "Déconnexion...", "de": "Verbindung wird getrennt...", "no": "Kobler fra...", "cs": "Odpojování..."},
    "text.main_antenna_beam_width_used_by_radio_telescope_tiling_and_peak_search": {
        "it": "Larghezza del fascio dell’antenna principale usata per la tassellatura Radio Telescope e la ricerca del picco.",
        "fr": "Largeur du faisceau de l’antenne principale utilisée pour le pavage Radio Telescope et la recherche du maximum.",
        "de": "Hauptantennen-Keulenbreite für Radio-Telescope-Kachelung und Spitzenwertsuche.",
        "no": "Hovedantennens strålebredde brukt til Radio Telescope-fliser og toppsøk.",
        "cs": "Šířka svazku hlavní antény používaná pro dlaždice Radio Telescope a hledání maxima.",
    },
    "text.antenna_beam": {"it": "Fascio antenna", "fr": "Faisceau d’antenne", "de": "Antennenkeule", "no": "Antennestråle", "cs": "Svazek antény"},
    "text.band_assignment_is_configured_once_below_in_the_common_band_rotator_table_this_profile_pag": {
        "it": "L’assegnazione della banda viene configurata una sola volta nella tabella comune Banda → Rotore. Questa pagina contiene soltanto l’hardware e l’algoritmo di ricerca del Rotore %1.",
        "fr": "L’affectation des bandes est configurée une seule fois dans le tableau commun Bande → Rotateur. Cette page contient uniquement le matériel et l’algorithme de recherche du Rotateur %1.",
        "de": "Die Bandzuordnung wird einmal in der gemeinsamen Tabelle Band → Rotor festgelegt. Diese Profilseite enthält nur Hardware und Suchalgorithmus für Rotor %1.",
        "no": "Båndtilordningen konfigureres én gang i den felles tabellen Bånd → rotor. Denne profilsiden inneholder bare maskinvare og søkealgoritme for rotor %1.",
        "cs": "Přiřazení pásem se nastavuje jednou ve společné tabulce Pásmo → rotátor. Tato stránka profilu obsahuje pouze hardware a vyhledávací algoritmus pro rotátor %1.",
    },
    "text.band_rotator_assignment_and_peak_search_span": {
        "it": "Assegnazione banda → rotore e intervallo di ricerca del picco",
        "fr": "Affectation bande → rotateur et plage de recherche du maximum",
        "de": "Band → Rotor-Zuordnung und Suchbereich für Spitzenwerte",
        "no": "Bånd → rotor-tilordning og søkeområde for topp",
        "cs": "Přiřazení pásmo → rotátor a rozsah hledání maxima",
    },
    "text.one_compact_table_assigns_each_operating_band_to_manual_rotator_1_rotator_2_or_rotator_3_t": {
        "it": "Una tabella compatta assegna ogni banda a Manuale, Rotore 1, Rotore 2 o Rotore 3. Gli intervalli di ricerca sono usati dal tracking QSO, dall’auto-peak e dal raffinamento del picco Radio Telescope.",
        "fr": "Un tableau compact affecte chaque bande à Manuel, Rotateur 1, 2 ou 3. Les plages de recherche sont utilisées par le suivi QSO, l’auto-peak et l’affinage du maximum Radio Telescope.",
        "de": "Eine kompakte Tabelle ordnet jedes Band Manuell, Rotor 1, Rotor 2 oder Rotor 3 zu. Die Suchbereiche dienen QSO-Tracking, Auto-Peak und der Radio-Telescope-Spitzenwertverfeinerung.",
        "no": "Én kompakt tabell tilordner hvert bånd til Manuell, rotor 1, rotor 2 eller rotor 3. Søkeområdene brukes av QSO-sporing, automatisk toppsøk og Radio Telescope-finjustering.",
        "cs": "Jedna kompaktní tabulka přiřazuje každé pásmo režimu Ručně, Rotátor 1, 2 nebo 3. Rozsahy hledání se používají pro sledování QSO, automatické hledání maxima a zpřesnění Radio Telescope.",
    },
    "text.manual": {"it": "Manuale", "fr": "Manuel", "de": "Manuell", "no": "Manuell", "cs": "Ručně"},
    "text.choose_which_rotator_controls_this_band_manual_means_no_automatic_band_assignment": {
        "it": "Scegli quale rotore controlla questa banda. Manuale significa nessuna assegnazione automatica.",
        "fr": "Choisissez le rotateur qui contrôle cette bande. Manuel signifie qu’aucune affectation automatique n’est utilisée.",
        "de": "Wählen, welcher Rotor dieses Band steuert. Manuell bedeutet keine automatische Bandzuordnung.",
        "no": "Velg hvilken rotor som styrer dette båndet. Manuell betyr ingen automatisk båndtilordning.",
        "cs": "Zvolte rotátor pro toto pásmo. Ručně znamená bez automatického přiřazení pásma.",
    },
    "text.azimuth_search_half_span_around_the_theoretical_bearing_30_means_30_degrees": {
        "it": "Semiampiezza della ricerca azimutale attorno alla direzione teorica. 30 significa ±30 gradi.",
        "fr": "Demi-plage de recherche en azimut autour du relèvement théorique. 30 signifie ±30 degrés.",
        "de": "Halbe Azimut-Suchspanne um die theoretische Peilung. 30 bedeutet ±30 Grad.",
        "no": "Halvt søkeområde i azimut rundt teoretisk peiling. 30 betyr ±30 grader.",
        "cs": "Poloviční rozsah hledání azimutu kolem teoretického směru. 30 znamená ±30 stupňů.",
    },
    "text.elevation_search_half_span_azimuth_only_rotators_ignore_this_value": {
        "it": "Semiampiezza della ricerca in elevazione. I rotori solo azimutali ignorano questo valore.",
        "fr": "Demi-plage de recherche en élévation. Les rotateurs azimutaux ignorent cette valeur.",
        "de": "Halbe Elevations-Suchspanne. Reine Azimutrotoren ignorieren diesen Wert.",
        "no": "Halvt søkeområde i elevasjon. Rotorer med bare azimut ignorerer verdien.",
        "cs": "Poloviční rozsah hledání elevace. Rotátory pouze s azimutem tuto hodnotu ignorují.",
    },
    "text.allow_automatic_signal_peak_search_refinement_on_this_band": {
        "it": "Consenti la ricerca e il raffinamento automatici del picco del segnale su questa banda.",
        "fr": "Autoriser la recherche et l’affinage automatiques du maximum du signal sur cette bande.",
        "de": "Automatische Signalsuche und Spitzenwertverfeinerung auf diesem Band zulassen.",
        "no": "Tillat automatisk søk og finjustering av signaltopp på dette båndet.",
        "cs": "Povolit automatické hledání a zpřesnění maxima signálu v tomto pásmu.",
    },
    "text.one_row_per_band_enable_auto_peak_choose_manual_rotator_1_2_3_then_set_the_local_az_el_sea": {
        "it": "Una riga per banda: abilita Auto peak, scegli Manuale/Rotore 1/2/3 e imposta l’intervallo locale di ricerca Az/El.",
        "fr": "Une ligne par bande : activez Auto peak, choisissez Manuel/Rotateur 1/2/3 puis définissez la plage locale Az/El.",
        "de": "Eine Zeile je Band: Auto-Peak aktivieren, Manuell/Rotor 1/2/3 wählen und lokalen Az/El-Suchbereich festlegen.",
        "no": "Én rad per bånd: aktiver automatisk toppsøk, velg Manuell/rotor 1/2/3 og angi lokalt Az/El-søkeområde.",
        "cs": "Jeden řádek na pásmo: povolte Auto peak, zvolte Ručně/Rotátor 1/2/3 a nastavte místní rozsah Az/El.",
    },
    "text.dedicated_serial_port_used_only_for_rts_dtr_ptt": {
        "it": "Porta seriale dedicata usata soltanto per il PTT RTS/DTR.",
        "fr": "Port série dédié utilisé uniquement pour le PTT RTS/DTR.",
        "de": "Eigener serieller Port nur für RTS/DTR-PTT.",
        "no": "Egen serieport som bare brukes til RTS/DTR-PTT.",
        "cs": "Vyhrazený sériový port používaný pouze pro PTT RTS/DTR.",
    },
    "text.disabled_because_ptt_is_handled_by_cat_hamlib_or_audio_only_mode_serial_rotator_ports_are_": {
        "it": "Disabilitato perché il PTT è gestito da CAT/Hamlib o dalla modalità solo audio; le porte seriali del rotore non vengono riservate qui.",
        "fr": "Désactivé car le PTT est géré par CAT/Hamlib ou par le mode audio seul ; les ports série des rotateurs ne sont pas réservés ici.",
        "de": "Deaktiviert, da PTT über CAT/Hamlib oder Nur-Audio läuft; serielle Rotorports werden hier nicht reserviert.",
        "no": "Deaktivert fordi PTT håndteres av CAT/Hamlib eller kun lyd; rotorens serieporter reserveres ikke her.",
        "cs": "Zakázáno, protože PTT řídí CAT/Hamlib nebo režim pouze zvuku; sériové porty rotátoru zde nejsou rezervovány.",
    },
    "text.import": {"it": "Importa", "fr": "Importer", "de": "Importieren", "no": "Importer", "cs": "Importovat"},
    "text.save_adif": {"it": "Salva ADIF", "fr": "Enregistrer ADIF", "de": "ADIF speichern", "no": "Lagre ADIF", "cs": "Uložit ADIF"},
    "text.save_csv": {"it": "Salva CSV", "fr": "Enregistrer CSV", "de": "CSV speichern", "no": "Lagre CSV", "cs": "Uložit CSV"},
    "text.copy_csv": {"it": "Copia CSV", "fr": "Copier CSV", "de": "CSV kopieren", "no": "Kopier CSV", "cs": "Kopírovat CSV"},
    "text.copy_adif": {"it": "Copia ADIF", "fr": "Copier ADIF", "de": "ADIF kopieren", "no": "Kopier ADIF", "cs": "Kopírovat ADIF"},
    "text.stats_pdf": {"it": "PDF statistiche", "fr": "PDF des statistiques", "de": "Statistik-PDF", "no": "Statistikk-PDF", "cs": "PDF statistik"},
    "text.columns": {"it": "Colonne", "fr": "Colonnes", "de": "Spalten", "no": "Kolonner", "cs": "Sloupce"},
    "add_qso_to_log": {"it": "Aggiungi QSO al registro", "fr": "Ajouter le QSO au journal", "de": "QSO zum Logbuch hinzufügen", "no": "Legg QSO til loggen", "cs": "Přidat QSO do deníku"},
    "insert_correspondent_callsign": {"it": "Inserisci prima il nominativo del corrispondente.", "fr": "Saisissez d’abord l’indicatif du correspondant.", "de": "Zuerst das Rufzeichen der Gegenstation eingeben.", "no": "Skriv inn motstasjonens kallesignal først.", "cs": "Nejprve zadejte volací značku protistanice."},
    "cannot_save_logbook": {"it": "Impossibile salvare il registro: %1", "fr": "Impossible d’enregistrer le journal : %1", "de": "Logbuch kann nicht gespeichert werden: %1", "no": "Kan ikke lagre loggen: %1", "cs": "Nelze uložit deník: %1"},
    "qso_saved_to_adif": {"it": "QSO con %1 salvato nel registro ADIF.%2", "fr": "QSO avec %1 enregistré dans le journal ADIF.%2", "de": "QSO mit %1 im ADIF-Logbuch gespeichert.%2", "no": "QSO med %1 lagret i ADIF-loggen.%2", "cs": "QSO s %1 uloženo do deníku ADIF.%2"},
    "clear_messages": {"it": "Cancella messaggi", "fr": "Effacer les messages", "de": "Nachrichten löschen", "no": "Tøm meldinger", "cs": "Vymazat zprávy"},
    "radio_telescope_caption": {"it": "Mappa termica del cielo Radio Telescope", "fr": "Carte thermique du ciel Radio Telescope", "de": "Radio-Telescope-Himmels-Heatmap", "no": "Radio Telescope-varmekart av himmelen", "cs": "Tepelná mapa oblohy Radio Telescope"},
    "cw_dual_rx_status": {"it": "RX A: clic sinistro · RX B: clic destro sulla waterfall", "fr": "RX A : clic gauche · RX B : clic droit sur la waterfall", "de": "RX A: Linksklick · RX B: Rechtsklick im Wasserfall", "no": "RX A: venstreklikk · RX B: høyreklikk i fossefallet", "cs": "RX A: levé tlačítko · RX B: pravé tlačítko ve waterfall"},
    "cw_disable_rx_b": {"it": "Disabilita RX B", "fr": "Désactiver RX B", "de": "RX B deaktivieren", "no": "Deaktiver RX B", "cs": "Zakázat RX B"},
    "cw_disable_rx_b_tooltip": {"it": "Rimuove il marcatore CW secondario blu. RX A continua a funzionare.", "fr": "Supprime le marqueur CW secondaire bleu. RX A continue de fonctionner.", "de": "Entfernt den blauen sekundären CW-Marker. RX A läuft weiter.", "no": "Fjerner den blå sekundære CW-markøren. RX A fortsetter.", "cs": "Odstraní modrou sekundární značku CW. RX A pokračuje."},
    "radio_telescope_settings": {"it": "Impostazioni scansione Radio Telescope", "fr": "Réglages du balayage Radio Telescope", "de": "Radio-Telescope-Scaneinstellungen", "no": "Innstillinger for Radio Telescope-skanning", "cs": "Nastavení skenování Radio Telescope"},
    "radio_telescope_rotator_altaz": {"it": "Disco cielo Alt-Az", "fr": "Disque du ciel Alt-Az", "de": "Alt-Az-Himmelsscheibe", "no": "Alt-Az-himmelskive", "cs": "Alt-Az disk oblohy"},
    "radio_telescope_rotator_az_only": {"it": "Anello azimutale", "fr": "Anneau azimutal", "de": "Azimutring", "no": "Azimutring", "cs": "Azimutální prstenec"},
    "radio_telescope_interpolate": {"it": "Interpola le celle adiacenti", "fr": "Interpoler les cellules adjacentes", "de": "Benachbarte Kacheln interpolieren", "no": "Interpoler nabofliser", "cs": "Interpolovat sousední dlaždice"},
    "radio_telescope_auto_point_peak": {"it": "Esegui auto-peak del rotore dopo la scansione", "fr": "Lancer l’auto-peak du rotateur après le balayage", "de": "Nach dem Scan Rotor-Auto-Peak ausführen", "no": "Kjør rotorens automatiske toppsøk etter skanning", "cs": "Po skenování spustit automatické hledání maxima rotátoru"},
    "radio_telescope_allow_no_rotator": {"it": "Test da banco senza rotore (non è una vera mappa del cielo)", "fr": "Essai sur banc sans rotateur (pas une vraie carte du ciel)", "de": "Prüfstandtest ohne Rotor (keine echte Himmelskarte)", "no": "Benktest uten rotor (ikke et ekte himmelkart)", "cs": "Test na stole bez rotátoru (nejde o skutečnou mapu oblohy)"},
    "radio_telescope_allow_no_rotator_tip": {"it": "Disabilitato per impostazione predefinita. Usalo soltanto per test audio/heatmap: l’antenna non si muove, quindi la mappa non rappresenta una vera scansione del cielo.", "fr": "Désactivé par défaut. À utiliser uniquement pour les essais audio/carte thermique : l’antenne ne bouge pas, la carte n’est donc pas un vrai relevé du ciel.", "de": "Standardmäßig deaktiviert. Nur für Audio-/Heatmap-Prüfstandtests verwenden: Die Antenne bewegt sich nicht, daher ist die Karte keine echte Himmelsdurchmusterung.", "no": "Deaktivert som standard. Brukes bare til lyd-/varmekarttest: antennen beveger seg ikke, så kartet er ikke en ekte himmelundersøkelse.", "cs": "Ve výchozím stavu vypnuto. Používejte pouze pro testy zvuku/tepelné mapy: anténa se nepohybuje, takže mapa není skutečný průzkum oblohy."},
    "radio_telescope_status_idle": {"it": "Heatmap inattiva", "fr": "Carte thermique inactive", "de": "Heatmap inaktiv", "no": "Varmekart inaktivt", "cs": "Tepelná mapa nečinná"},
    "radio_telescope_progress_idle": {"it": "Scansione arrestata", "fr": "Balayage arrêté", "de": "Scan angehalten", "no": "Skanning stoppet", "cs": "Skenování zastaveno"},
    "radio_telescope_scan_geometry": {"it": "Geometria di scansione", "fr": "Géométrie du balayage", "de": "Scangeometrie", "no": "Skannegeometri", "cs": "Geometrie skenování"},
    "radio_telescope_beamwidth": {"it": "Larghezza fascio antenna", "fr": "Largeur du faisceau d’antenne", "de": "Antennenkeulenbreite", "no": "Antennens strålebredde", "cs": "Šířka svazku antény"},
    "radio_telescope_dwell": {"it": "Integrazione / cella", "fr": "Intégration / cellule", "de": "Messzeit / Kachel", "no": "Måletid / flis", "cs": "Doba měření / dlaždice"},
    "radio_telescope_settle": {"it": "Attesa dopo il movimento", "fr": "Stabilisation après déplacement", "de": "Beruhigungszeit nach Bewegung", "no": "Stabilisering etter bevegelse", "cs": "Ustálení po pohybu"},
    "radio_telescope_low_freq": {"it": "Limite audio inferiore", "fr": "Limite audio basse", "de": "Untere Audiogrenze", "no": "Nedre lydgrense", "cs": "Dolní mez zvuku"},
    "radio_telescope_high_freq": {"it": "Limite audio superiore", "fr": "Limite audio haute", "de": "Obere Audiogrenze", "no": "Øvre lydgrense", "cs": "Horní mez zvuku"},
    "radio_telescope_start_scan": {"it": "Avvia scansione", "fr": "Démarrer le balayage", "de": "Scan starten", "no": "Start skanning", "cs": "Spustit skenování"},
    "radio_telescope_stop_scan": {"it": "Ferma scansione", "fr": "Arrêter le balayage", "de": "Scan stoppen", "no": "Stopp skanning", "cs": "Zastavit skenování"},
    "radio_telescope_reset_map": {"it": "Azzera mappa", "fr": "Réinitialiser la carte", "de": "Karte zurücksetzen", "no": "Tilbakestill kart", "cs": "Resetovat mapu"},
    "radio_telescope_reset_map_tip": {"it": "Cancella le celle misurate e ridisegna la griglia di scansione vuota.", "fr": "Efface les cellules mesurées et redessine la grille de balayage vide.", "de": "Gemessene Kacheln löschen und das leere Scanraster neu zeichnen.", "no": "Tøm målte fliser og tegn det tomme skannerutenettet på nytt.", "cs": "Vymaže změřené dlaždice a znovu vykreslí prázdnou skenovací mřížku."},
    "radio_telescope_export_csv": {"it": "Esporta CSV", "fr": "Exporter CSV", "de": "CSV exportieren", "no": "Eksporter CSV", "cs": "Exportovat CSV"},
    "radio_telescope_point_max": {"it": "Auto peak", "fr": "Auto peak", "de": "Auto-Peak", "no": "Automatisk topp", "cs": "Auto peak"},
    "radio_telescope_point_max_tip": {"it": "Usa l’algoritmo auto-peak selezionato e la heatmap misurata per affinare o puntare la direzione più intensa.", "fr": "Utilise l’algorithme auto-peak sélectionné et la carte mesurée pour affiner ou pointer la direction la plus forte.", "de": "Mit dem gewählten Auto-Peak-Algorithmus und der gemessenen Heatmap die stärkste Richtung verfeinern oder anfahren.", "no": "Bruk valgt algoritme for automatisk toppsøk og målt varmekart til å finjustere eller peke mot sterkeste retning.", "cs": "Použije zvolený algoritmus Auto peak a změřenou tepelnou mapu ke zpřesnění nebo zaměření nejsilnějšího směru."},
    "radio_telescope_measurements": {"it": "Celle misurate", "fr": "Cellules mesurées", "de": "Gemessene Kacheln", "no": "Målte fliser", "cs": "Změřené dlaždice"},
    "radio_telescope_export_csv_title": {"it": "Esporta CSV Radio Telescope", "fr": "Exporter le CSV Radio Telescope", "de": "Radio-Telescope-CSV exportieren", "no": "Eksporter Radio Telescope-CSV", "cs": "Exportovat CSV Radio Telescope"},
    "radio_telescope_status_ready": {"it": "Rotore pronto. Avvia la scansione quando RX è attivo.", "fr": "Rotateur prêt. Démarrez le balayage lorsque RX est actif.", "de": "Rotor bereit. Scan starten, sobald RX aktiv ist.", "no": "Rotor klar. Start skanning når RX er aktiv.", "cs": "Rotátor připraven. Spusťte skenování, když je RX aktivní."},
    "radio_telescope_overlay_scanning": {"it": "Scansione attiva", "fr": "Balayage actif", "de": "Scan aktiv", "no": "Skanning aktiv", "cs": "Skenování aktivní"},
    "radio_telescope_overlay_idle": {"it": "In attesa", "fr": "En attente", "de": "Warten", "no": "Venter", "cs": "Čekání"},
    "radio_telescope_bench_warning": {"it": "Modalità test da banco: rotore non richiesto; la heatmap non è una vera mappa del cielo.", "fr": "Mode essai sur banc : rotateur non requis ; la carte thermique n’est pas une vraie carte du ciel.", "de": "Prüfstandmodus: kein Rotor erforderlich; die Heatmap ist keine echte Himmelskarte.", "no": "Benktestmodus: rotor er ikke nødvendig; varmekartet er ikke et ekte himmelkart.", "cs": "Režim testu na stole: rotátor není nutný; tepelná mapa není skutečná mapa oblohy."},
    "radio_telescope_no_rotator_controller": {"it": "Nessun controller rotore disponibile. Connetti/configura un rotore oppure abilita esplicitamente il test da banco senza rotore.", "fr": "Aucun contrôleur de rotateur disponible. Connectez/configurez un rotateur ou activez explicitement l’essai sur banc sans rotateur.", "de": "Kein Rotorcontroller verfügbar. Einen Rotor verbinden/konfigurieren oder den Prüfstandtest ohne Rotor ausdrücklich aktivieren.", "no": "Ingen rotorkontroller er tilgjengelig. Koble til/konfigurer en rotor eller aktiver benktest uten rotor uttrykkelig.", "cs": "Není k dispozici žádný řadič rotátoru. Připojte/nakonfigurujte rotátor nebo výslovně povolte test na stole bez rotátoru."},
    "radio_telescope_rotator_disabled": {"it": "Il rotore è disabilitato per la banda o il profilo corrente. Abilitalo prima di avviare una scansione del cielo.", "fr": "Le rotateur est désactivé pour la bande ou le profil actuel. Activez-le avant de lancer un balayage du ciel.", "de": "Der Rotor ist für das aktuelle Band/Profil deaktiviert. Vor einem Himmelsscan aktivieren.", "no": "Rotoren er deaktivert for gjeldende bånd/profil. Aktiver den før himmelskanning.", "cs": "Rotátor je pro aktuální pásmo/profil zakázán. Před skenováním oblohy jej povolte."},
    "radio_telescope_rotator_disconnected": {"it": "Il rotore non è connesso. Connetti il rotore selezionato prima di avviare una scansione del cielo.", "fr": "Le rotateur n’est pas connecté. Connectez le rotateur sélectionné avant de lancer un balayage du ciel.", "de": "Der Rotor ist nicht verbunden. Den ausgewählten Rotor vor dem Himmelsscan verbinden.", "no": "Rotoren er ikke tilkoblet. Koble til valgt rotor før himmelskanning.", "cs": "Rotátor není připojen. Před skenováním oblohy připojte vybraný rotátor."},
    "radio_telescope_altaz_requires_el": {"it": "Il disco cielo Alt-Az richiede un rotore con elevazione. Scegli Anello azimutale oppure abilita l’elevazione nel profilo rotore.", "fr": "Le disque du ciel Alt-Az nécessite un rotateur avec élévation. Choisissez Anneau azimutal ou activez l’élévation dans le profil.", "de": "Die Alt-Az-Himmelsscheibe benötigt einen Rotor mit Elevation. Azimutring wählen oder Elevation im Rotorprofil aktivieren.", "no": "Alt-Az-himmelskiven krever en rotor med elevasjon. Velg Azimutring eller aktiver elevasjon i rotorprofilen.", "cs": "Alt-Az disk oblohy vyžaduje rotátor s elevací. Zvolte Azimutální prstenec nebo povolte elevaci v profilu rotátoru."},
    "radio_telescope_rotator_ready": {"it": "Rotore pronto per la scansione Radio Telescope.", "fr": "Rotateur prêt pour le balayage Radio Telescope.", "de": "Rotor für Radio-Telescope-Scan bereit.", "no": "Rotor klar for Radio Telescope-skanning.", "cs": "Rotátor připraven pro skenování Radio Telescope."},
    "radio_telescope_no_tiles_in_limits": {"it": "Scansione Radio Telescope bloccata: nessuna cella rientra nei limiti o finecorsa configurati del rotore.", "fr": "Balayage Radio Telescope bloqué : aucune cellule ne se trouve dans les limites/butées configurées du rotateur.", "de": "Radio-Telescope-Scan blockiert: Keine Kachel liegt innerhalb der konfigurierten Rotorgrenzen/Endanschläge.", "no": "Radio Telescope-skanning blokkert: ingen flis er innenfor konfigurerte rotorgrenser/endestopp.", "cs": "Skenování Radio Telescope zablokováno: žádná dlaždice není v nastavených limitech/koncových bodech rotátoru."},
    "radio_telescope_status_done": {"it": "Scansione completata: arresto automatico.", "fr": "Balayage terminé : arrêt automatique.", "de": "Scan abgeschlossen: automatischer Stopp.", "no": "Skanning fullført: automatisk stopp.", "cs": "Skenování dokončeno: automatické zastavení."},
    "radio_telescope_status_stopped": {"it": "Scansione arrestata.", "fr": "Balayage arrêté.", "de": "Scan gestoppt.", "no": "Skanning stoppet.", "cs": "Skenování zastaveno."},
    "radio_telescope_park_ready": {"it": "Posizione di parcheggio/inizio raggiunta; avvio della scansione del cielo.", "fr": "Position de parking/départ atteinte ; démarrage du balayage du ciel.", "de": "Park-/Startposition erreicht; Himmelsscan wird gestartet.", "no": "Park-/startposisjon nådd; starter himmelskanning.", "cs": "Dosažena parkovací/startovní poloha; spouští se skenování oblohy."},
    "msk144_rx_tx_settings": {"it": "Impostazioni RX/TX MSK144", "fr": "Réglages RX/TX MSK144", "de": "MSK144 RX/TX-Einstellungen", "no": "MSK144 RX/TX-innstillinger", "cs": "Nastavení RX/TX MSK144"},
    "msk144_short_messages": {"it": "Messaggi brevi", "fr": "Messages courts", "de": "Kurznachrichten", "no": "Korte meldinger", "cs": "Krátké zprávy"},
    "msk144_tx_first": {"it": "TX nel primo periodo", "fr": "TX pendant la première période", "de": "TX in erster Periode", "no": "TX i første periode", "cs": "TX v první periodě"},
    "msk144_status_idle": {"it": "MSK144: inattivo", "fr": "MSK144 : inactif", "de": "MSK144: inaktiv", "no": "MSK144: inaktiv", "cs": "MSK144: nečinný"},
    "standard_messages": {"it": "Messaggi standard", "fr": "Messages standard", "de": "Standardnachrichten", "no": "Standardmeldinger", "cs": "Standardní zprávy"},
    "menu_decode": {"it": "Decodifica", "fr": "Décodage", "de": "Dekodieren", "no": "Dekoding", "cs": "Dekódování"},
    "msk144_decode_depth": {"it": "Profondità decodifica MSK144", "fr": "Profondeur de décodage MSK144", "de": "MSK144-Dekodiertiefe", "no": "MSK144-dekodedybde", "cs": "Hloubka dekódování MSK144"},
    "msk144_depth_fast_hint": {"it": "Mappatura MSHV: solo decoder dei ping brevi.", "fr": "Correspondance MSHV : décodeur de pings courts uniquement.", "de": "MSHV-Zuordnung: nur Kurznachrichten-/Ping-Decoder.", "no": "MSHV-kartlegging: bare dekoder for korte ping.", "cs": "Mapování MSHV: pouze dekodér krátkých pingů."},
    "msk144_depth_normal_hint": {"it": "Impostazione MSHV predefinita: decoder ping brevi più medie coerenti su 4 frame.", "fr": "Réglage MSHV par défaut : décodeur de pings courts plus moyennes cohérentes sur 4 trames.", "de": "MSHV-Standard: Kurzping-Decoder plus kohärente 4-Frame-Mittelungen.", "no": "MSHV-standard: dekoder for korte ping pluss koherente gjennomsnitt over 4 rammer.", "cs": "Výchozí MSHV: dekodér krátkých pingů plus koherentní průměry ze 4 rámců."},
    "msk144_depth_deep_hint": {"it": "MSK144 profondo MSHV: decoder ping brevi più medie coerenti su 4, 5 e 7 frame.", "fr": "MSK144 profond MSHV : décodeur de pings courts plus moyennes cohérentes sur 4, 5 et 7 trames.", "de": "MSHV Deep MSK144: Kurzping-Decoder plus kohärente 4-, 5- und 7-Frame-Mittelungen.", "no": "MSHV dyp MSK144: dekoder for korte ping pluss koherente gjennomsnitt over 4, 5 og 7 rammer.", "cs": "Hluboké MSK144 MSHV: dekodér krátkých pingů plus koherentní průměry ze 4, 5 a 7 rámců."},
    "q65_rx_tx_settings": {"it": "Impostazioni RX/TX Q65", "fr": "Réglages RX/TX Q65", "de": "Q65 RX/TX-Einstellungen", "no": "Q65 RX/TX-innstillinger", "cs": "Nastavení RX/TX Q65"},
    "q65_avg_decode": {"it": "Media", "fr": "Moyenne", "de": "Mittelung", "no": "Gjennomsnitt", "cs": "Průměrování"},
    "q65_auto_clear_avg": {"it": "Azzera automaticamente AVG", "fr": "Effacer automatiquement AVG", "de": "AVG automatisch löschen", "no": "Tøm AVG automatisk", "cs": "Automaticky vymazat AVG"},
    "q65_single_decode": {"it": "Decodifica singola", "fr": "Décodage unique", "de": "Einzeldekodierung", "no": "Enkeltdekoding", "cs": "Jednorázové dekódování"},
    "q65_ap_decode": {"it": "Decodifica AP", "fr": "Décodage AP", "de": "AP-Dekodierung", "no": "AP-dekoding", "cs": "AP dekódování"},
    "q65_max_drift": {"it": "Deriva massima", "fr": "Dérive maximale", "de": "Maximale Drift", "no": "Maksimal drift", "cs": "Maximální drift"},
    "q65_eme_delay": {"it": "Ritardo EME", "fr": "Délai EME", "de": "EME-Verzögerung", "no": "EME-forsinkelse", "cs": "Zpoždění EME"},
    "q65_clear_avg": {"it": "Azzera AVG", "fr": "Effacer AVG", "de": "AVG löschen", "no": "Tøm AVG", "cs": "Vymazat AVG"},
    "q65_status_idle": {"it": "Q65: inattivo", "fr": "Q65 : inactif", "de": "Q65: inaktiv", "no": "Q65: inaktiv", "cs": "Q65: nečinný"},
    "decode_depth": {"it": "Decodifica", "fr": "Décodage", "de": "Dekodierung", "no": "Dekoding", "cs": "Dekódování"},
    "cw_tracked_ab": {"it": "Tracciato A: %1 WPM · B: %2 WPM", "fr": "Suivi A : %1 MPM · B : %2 MPM", "de": "Verfolgt A: %1 WPM · B: %2 WPM", "no": "Sporet A: %1 WPM · B: %2 WPM", "cs": "Sledováno A: %1 WPM · B: %2 WPM"},
    "action.exit.safe": {"it": "Chiudi MadModem in modo sicuro.", "fr": "Fermer MadModem en toute sécurité.", "de": "MadModem sicher beenden.", "no": "Lukk MadModem på en sikker måte.", "cs": "Bezpečně ukončit MadModem."},
    "scheduler_wefax_group": {"it": "MeteoFax / RX WEFAX HF", "fr": "MeteoFax / RX WEFAX HF", "de": "MeteoFax / HF-WEFAX RX", "no": "MeteoFax / HF WEFAX RX", "cs": "MeteoFax / HF WEFAX RX"},
    "seq_completed": {"it": "QSO completato / invia 73 se necessario", "fr": "QSO terminé / envoyer 73 si nécessaire", "de": "QSO abgeschlossen / bei Bedarf 73 senden", "no": "QSO fullført / send 73 ved behov", "cs": "QSO dokončeno / podle potřeby odeslat 73"},
    "seq_send_rr73": {"it": "ricevuto rapporto R; selezionato RR73", "fr": "rapport R reçu ; RR73 sélectionné", "de": "R-Bericht empfangen; RR73 gewählt", "no": "R-rapport mottatt; RR73 valgt", "cs": "přijat R-report; zvoleno RR73"},
    "seq_send_r_report": {"it": "rapporto ricevuto; selezionato rapporto R", "fr": "rapport reçu ; rapport R sélectionné", "de": "Bericht empfangen; R-Bericht gewählt", "no": "rapport mottatt; R-rapport valgt", "cs": "přijat report; zvolen R-report"},
    "seq_send_report": {"it": "chiamata/locator diretto ricevuto; selezionato rapporto", "fr": "appel/locator dirigé reçu ; rapport sélectionné", "de": "gerichteter Ruf/Locator empfangen; Bericht gewählt", "no": "rettet anrop/lokator mottatt; rapport valgt", "cs": "přijata směrovaná výzva/lokátor; zvolen report"},
    "rotator_connected": {"it": "Connesso", "fr": "Connecté", "de": "Verbunden", "no": "Tilkoblet", "cs": "Připojeno"},
    "rotator_disconnected": {"it": "Disconnesso", "fr": "Déconnecté", "de": "Getrennt", "no": "Frakoblet", "cs": "Odpojeno"},
    "rotator_connect_missing_endpoint": {"it": "Connessione bloccata: seleziona prima il modello del rotore e la porta COM/endpoint rotctld.", "fr": "Connexion bloquée : sélectionnez d’abord le modèle du rotateur et le port COM/point rotctld.", "de": "Verbindung blockiert: zuerst Rotormodell und COM-/rotctld-Endpunkt wählen.", "no": "Tilkobling blokkert: velg rotormodell og COM-/rotctld-endepunkt først.", "cs": "Připojení zablokováno: nejprve zvolte model rotátoru a COM/rotctld endpoint."},
    "radio_telescope_progress_blocked": {"it": "Scansione bloccata: rotore non pronto.", "fr": "Balayage bloqué : rotateur non prêt.", "de": "Scan blockiert: Rotor nicht bereit.", "no": "Skanning blokkert: rotor ikke klar.", "cs": "Skenování zablokováno: rotátor není připraven."},
    "ptt_test_on_one_second": {"it": "Test PTT attivo per 1 secondo.", "fr": "Test PTT actif pendant 1 seconde.", "de": "PTT-Test für 1 Sekunde EIN.", "no": "PTT-test PÅ i 1 sekund.", "cs": "Test PTT zapnut na 1 sekundu."},
    "text.qso_info": {"it": "Informazioni QSO", "fr": "Informations QSO", "de": "QSO-Informationen", "no": "QSO-informasjon", "cs": "Informace QSO"},
    "text.rotator_unavailable": {"it": "Rotore non disponibile", "fr": "Rotateur indisponible", "de": "Rotor nicht verfügbar", "no": "Rotor utilgjengelig", "cs": "Rotátor není k dispozici"},
    "text.auto_polarity": {"it": "Polarità automatica", "fr": "Polarité automatique", "de": "Automatische Polarität", "no": "Automatisk polaritet", "cs": "Automatická polarita"},
    "text.speed_hint": {"it": "Velocità indicativa", "fr": "Vitesse indicative", "de": "Geschwindigkeitshinweis", "no": "Hastighetsestimat", "cs": "Odhad rychlosti"},
    "text.paper_speed": {"it": "Velocità carta", "fr": "Vitesse du papier", "de": "Papiergeschwindigkeit", "no": "Papirhastighet", "cs": "Rychlost papíru"},
    "text.paper_zoom": {"it": "Zoom carta", "fr": "Zoom du papier", "de": "Papierzoom", "no": "Papirzoom", "cs": "Přiblížení papíru"},
    "text.enable_slow_afc_for_the_mfsk_tone_bank_receiver": {"it": "Abilita AFC lento per il ricevitore MFSK a banco di toni.", "fr": "Activer l’AFC lent pour le récepteur MFSK à banque de tons.", "de": "Langsame AFC für den MFSK-Tonbankempfänger aktivieren.", "no": "Aktiver langsom AFC for MFSK-tonebankmottakeren.", "cs": "Povolit pomalé AFC pro přijímač MFSK s bankou tónů."},
}
