#!/usr/bin/env python3
"""
MadModem UI translation dictionary maintenance helper.

The application uses a light INI based runtime dictionary.  This script harvests:
  * explicit uiText("key", "English fallback") calls from C++/headers;
  * visible strings from Qt Designer .ui files.
It then refreshes translations/ui_*.ini and guarantees that each language has the
same key set.  The non-English dictionaries use curated exact translations for
common MadModem UI text plus conservative technical-term preservation.
"""
from __future__ import annotations

import ast
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from collections import OrderedDict

ROOT = Path(__file__).resolve().parents[1]
TRANS_DIR = ROOT / "translations"
LANGS = ["en", "it", "fr", "de", "no", "cs"]

# ---------------------------------------------------------------------------
# Key generation matching MainWindow::uiTextFromSource().
# ---------------------------------------------------------------------------
def norm_key(source: str) -> str:
    normalized = []
    last_us = False
    for ch in source:
        if ch.isalnum():
            normalized.append(ch.lower())
            last_us = False
        else:
            if not last_us:
                normalized.append("_")
                last_us = True
    out = "".join(normalized).strip("_") or "empty"
    return out[:90]


def unescape_cpp(s: str) -> str:
    try:
        return ast.literal_eval('"' + s.replace('"', r'\"') + '"')
    except Exception:
        return s


def read_ini(path: Path) -> OrderedDict[str, str]:
    d: OrderedDict[str, str] = OrderedDict()
    if not path.exists():
        return d
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("[") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        d[k.strip()] = v.strip().replace("\\n", "\n")
    return d


def write_ini(path: Path, lang: str, data: OrderedDict[str, str]) -> None:
    def esc(v: str) -> str:
        return v.replace("\n", "\\n")
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(f"# MadModem UI dictionary {lang}\n")
        f.write("# Generated by tools/update_ui_translations.py. Edit the exact phrase maps there.\n")
        for k, v in data.items():
            f.write(f"{k}={esc(v)}\n")


def harvest_keys() -> OrderedDict[str, str]:
    out: OrderedDict[str, str] = OrderedDict()

    ui_pat = re.compile(r'uiText\s*\(\s*"([^"]+)"\s*,\s*"((?:\\.|[^"])*)"', re.S)
    for p in sorted(list(ROOT.rglob("*.cpp")) + list(ROOT.rglob("*.h"))):
        if "/build-" in str(p) or "/third_party/" in str(p):
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        for m in ui_pat.finditer(text):
            key = m.group(1)
            fallback = unescape_cpp(m.group(2))
            if key == "key" and fallback == "fallback":
                continue
            out[key] = fallback

        # Dialog-local translators use either L("English source") or
        # L("stable_key", "English fallback").  Harvest both forms.  The
        # two-argument form must be harvested by its real stable key; otherwise
        # generated dictionaries show marker text such as scheduler_dialog_title.
        two_arg_l = re.compile(
            r'\bL\s*\(\s*(?:QStringLiteral\s*\(\s*)?"((?:\\.|[^"])*)"\s*\)?\s*,\s*'
            r'(?:QStringLiteral\s*\(\s*)?"((?:\\.|[^"])*)"',
            re.S,
        )
        two_arg_spans = []
        for m in two_arg_l.finditer(text):
            key = unescape_cpp(m.group(1)).strip()
            fallback = unescape_cpp(m.group(2)).strip()
            two_arg_spans.append((m.start(), m.end()))
            if key and fallback:
                out.setdefault(key, fallback)

        def inside_two_arg_l(pos: int) -> bool:
            return any(a <= pos < b for a, b in two_arg_spans)

        # Single-argument L("English source") and runtime dictionary calls
        # resolve through MainWindow::uiTextFromSource()/MadModemI18n.  Skip
        # marker-like one-word keys to avoid polluting dictionaries with
        # internal ids.
        local_text_call_patterns = [
            r'\bL\s*\(\s*(?:QStringLiteral\s*\(\s*)?"((?:\\.|[^"])*)"',
            r'\bL18n\s*\(\s*(?:QStringLiteral\s*\(\s*)?"((?:\\.|[^"])*)"',
            r'\bP18n\s*\(\s*(?:QStringLiteral\s*\(\s*)?"((?:\\.|[^"])*)"',
            r'\bMadModemI18n::text\s*\(\s*(?:QStringLiteral\s*\(\s*)?"((?:\\.|[^"])*)"',
            r'(?<![A-Za-z0-9_:])T\s*\(\s*(?:QStringLiteral\s*\(\s*)?"((?:\\.|[^"])*)"',
            r'\bMadModemI18n::placeholder\s*\(\s*(?:QStringLiteral\s*\(\s*)?"((?:\\.|[^"])*)"',
            r'(?<![A-Za-z0-9_:])tr\s*\(\s*"((?:\\.|[^"])*)"',
            r'\bQObject::tr\s*\(\s*"((?:\\.|[^"])*)"',
        ]
        for call_pat in local_text_call_patterns:
            for m in re.finditer(call_pat, text, re.S):
                if call_pat.startswith(r'\bL') and inside_two_arg_l(m.start()):
                    continue
                source = unescape_cpp(m.group(1)).strip()
                if not source:
                    continue
                if re.fullmatch(r'[a-z0-9_]+', source) and '_' in source:
                    continue
                if call_pat.startswith(r'\bMadModemI18n::placeholder') or call_pat.startswith(r'\bP18n'):
                    out.setdefault("placeholder." + norm_key(source), source)
                else:
                    out.setdefault("text." + norm_key(source), source)

    # Selected visible/runtime C++ strings.  This is intentionally not a generic
    # string-literal scraper: it only harvests strings passed to common UI/log
    # APIs where the user can see the text.  File names, object names, settings
    # keys and protocol constants remain excluded.
    visible_patterns = [
        (re.compile(r'appendLog\s*\(\s*"((?:\\.|[^"])*)"', re.S), "log"),
        (re.compile(r'appendLog\s*\(\s*QString\s*\(\s*"((?:\\.|[^"])*)"', re.S), "log"),
        (re.compile(r'appendLog\s*\(\s*QStringLiteral\s*\(\s*"((?:\\.|[^"])*)"', re.S), "log"),
        (re.compile(r'QMessageBox::(?:information|warning|critical|question)\s*\([^;]*?,\s*(?:QStringLiteral\s*\()?"((?:\\.|[^"])*)"\)?\s*,\s*(?:QStringLiteral\s*\()?"((?:\\.|[^"])*)"', re.S), "textpair"),
        (re.compile(r'new\s+(?:QLabel|QPushButton|QCheckBox|QGroupBox|QAction)\s*\(\s*(?:QStringLiteral\s*\()?"((?:\\.|[^"])*)"', re.S), "text"),
        (re.compile(r'(?:setWindowTitle|setText|setToolTip|setStatusTip|addItem|addTab|addAction|addMenu)\s*\(\s*(?:QStringLiteral\s*\()?"((?:\\.|[^"])*)"', re.S), "text"),
        (re.compile(r'QStringList\s*\(\s*\)\s*<<\s*"((?:\\.|[^"])*)"', re.S), "text"),
        (re.compile(r'<<\s*"((?:\\.|[^"])*)"', re.S), "text"),
    ]

    def plausible_user_text(src: str) -> bool:
        if src in {"MadModem 0.5.0"}:
            return False
        if not src or len(src) > 180:
            return False
        if src.startswith(":/") or src.startswith("/") or src.startswith("../"):
            return False
        if re.fullmatch(r'[A-Za-z0-9_./:-]+', src) and ('_' in src or '/' in src or src.endswith(('.cpp', '.h', '.ui', '.png', '.wav', '.adi'))):
            return False
        if src in {"default", "none", "cat_hamlib", "serial_rts", "serial_dtr", "mshv"}:
            return False
        return any(ch.isalpha() for ch in src)

    for p in sorted(list(ROOT.rglob("*.cpp")) + list(ROOT.rglob("*.h"))):
        ps = str(p)
        if "/build-" in ps or "/third_party/" in ps:
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        for pat, kind in visible_patterns:
            for m in pat.finditer(text):
                if kind == "textpair":
                    values = [unescape_cpp(m.group(1)), unescape_cpp(m.group(2))]
                    prefixes = ["text", "text"]
                else:
                    values = [unescape_cpp(m.group(1))]
                    prefixes = [kind]
                for value, prefix in zip(values, prefixes):
                    value = value.strip()
                    if plausible_user_text(value):
                        out.setdefault(prefix + "." + norm_key(value), value)

    # Explicit runtime keys which are not convenient to harvest from concatenated
    # rich-text literals but are still shown to the user.
    out.setdefault("help.autoqso_flow_html", (
        "<h2>MM Flow editor</h2>"
        "<p>This editor is becoming the visual programming layer for MadModem. "
        "Today it stores and validates the flow graph; live PTT/audio/CAT safety still remains in the scheduler.</p>"
        "<h3>Basic editing</h3>"
        "<ul>"
        "<li><b>Create a block:</b> press one of the + buttons, choose the type, title and note.</li>"
        "<li><b>Create an arrow:</b> select two blocks, press <b>Connect arrow</b>, choose the output port if needed.</li>"
        "<li><b>Delete an arrow:</b> click the arrow line and press <b>Delete arrows</b> or the Delete key.</li>"
        "<li><b>Delete a block:</b> select the block and press Delete. Connected arrows are removed too.</li>"
        "<li><b>Edit:</b> select exactly one block and press <b>Edit selected</b>. Shortcuts: Delete, Ctrl+E, Ctrl+L, Ctrl+H.</li>"
        "</ul>"
        "<h3>Programming blocks</h3>"
        "<ul>"
        "<li><b>Variable:</b> set/copy/increment/clear/list/map values.</li>"
        "<li><b>Compare:</b> compare variables, constants, decoded calls, bands, modes and regex matches.</li>"
        "<li><b>Loop:</b> iterate over decodes, candidates, log rows or bounded counters. Use next/done or loop/exit ports.</li>"
        "<li><b>I/O:</b> keyboard input, popup message/question, status message, log message, table output.</li>"
        "<li><b>Timer:</b> FT slot wait, decode-window wait, retry delay, interval, watchdog, UTC time trigger.</li>"
        "<li><b>Math:</b> arithmetic plus radio helpers such as locator distance/bearing.</li>"
        "</ul>"
        "<h3>Safety model</h3>"
        "<p>Flows may request abstract app actions. Dangerous operations such as TX, PTT, audio start, CAT QSY, file writes and scheduler operations must pass through MadModem's runtime guards.</p>"
    ))

    # Visible strings from Qt Designer forms.  These are translated through
    # MainWindow::translateObjectTree() using text.<normalized-source> keys.
    for ui in sorted(ROOT.rglob("*.ui")):
        try:
            tree = ET.parse(ui)
        except ET.ParseError:
            continue
        for node in tree.iter("string"):
            source = "".join(node.itertext()).strip()
            if not source:
                continue
            out.setdefault("text." + norm_key(source), source)
            out.setdefault("placeholder." + norm_key(source), source)

    return out

# ---------------------------------------------------------------------------
# Curated phrase translations.  Technical mode names/callsigns/units are kept
# as-is unless translating them improves readability.
# ---------------------------------------------------------------------------
EXACT: dict[str, dict[str, str]] = {
    "it": {
        "About MM": "Informazioni su MM",
        "Audio / PTT settings": "Impostazioni audio / PTT",
        "Audio / PTT settings...": "Impostazioni audio / PTT...",
        "Exit": "Esci",
        "+ Logbook...": "+ Registro QSO...",
        "Logbook": "Registro QSO",
        "Logbook file settings...": "Impostazioni file registro QSO...",
        "Analyze WEFAX WAV...": "Analizza WAV WEFAX...",
        "Analyze SSTV WAV...": "Analizza WAV SSTV...",
        "Analyze WAV...": "Analizza WAV...",
        "CAT / Rig...": "CAT / Radio...",
        "CAT / Rig control": "Controllo CAT / radio",
        "Soundcard calibration...": "Calibrazione scheda audio...",
        "Soundcard Calibration": "Calibrazione scheda audio",
        "SSTV image editor...": "Editor immagini SSTV...",
        "Open SSTV editor...": "Apri editor SSTV...",
        "User/QTH...": "Utente/QTH...",
        "Text macros...": "Macro testuali...",
        "File": "File",
        "Settings": "Impostazioni",
        "Help": "Aiuto",
        "Language": "Lingua",
        "Mode": "Modo",
        "Status": "Stato",
        "Activity": "Attività",
        "Time": "Ora",
        "Frequency": "Frequenza",
        "Freq": "Freq",
        "Message": "Messaggio",
        "Dir": "Dir",
        "Band": "Banda",
        "connected": "connesso",
        "not connected": "non connesso",
        "ON": "ON",
        "OFF": "OFF",
        "Refresh": "Aggiorna",
        "Reset view": "Ripristina vista",
        "Save map...": "Salva mappa...",
        "Print map...": "Stampa mappa...",
        "QSO map": "Mappa QSO",
        "Show home paths": "Mostra percorsi da casa",
        "Show Maidenhead grid": "Mostra griglia Maidenhead",
        "Overlay 4-character Maidenhead squares; worked squares become green.": "Sovrappone i quadrati Maidenhead a 4 caratteri; i quadrati collegati diventano verdi.",
        "Rig / CAT": "Radio / CAT",
        "CAT: disabled": "CAT: disabilitato",
        "CAT status": "Stato CAT",
        "Hamlib: not compiled in": "Hamlib: non compilato",
        "PTT: serial RTS / none": "PTT: RTS seriale / nessuno",
        "Stop TX before changing CAT / rig-control settings.": "Ferma la TX prima di cambiare le impostazioni CAT / controllo radio.",
        "RX audio marker": "Marcatore audio RX",
        "TX audio marker": "Marcatore audio TX",
        "Load image...": "Carica immagine...",
        "Send SSTV": "Invia SSTV",
        "Start image TX": "Avvia TX immagine",
        "Stop TX": "Ferma TX",
        "STOP": "STOP",
        "Call": "Nominativo",
        "Name": "Nome",
        "Info": "Info",
        "QTH": "QTH",
        "No SSTV TX image": "Nessuna immagine SSTV TX",
        "FT4/FT8 activity and QSO control": "Attività FT4/FT8 e controllo QSO",
        "Received decodes": "Decodifiche ricevute",
        "Clear decodes": "Cancella decodifiche",
        "Clears the visible FT4/FT8 decode list and transient waterfall CQ/reply callouts.": "Cancella la lista visibile delle decodifiche FT4/FT8 e i richiami CQ/risposta temporanei sulla waterfall.",
        "Auto-scroll": "Scorrimento automatico",
        "Keep the decode table scrolled to the newest line while receiving.": "Mantiene la tabella delle decodifiche sull'ultima riga durante la ricezione.",
        "QSO activity / RX frequency": "Attività QSO / frequenza RX",
        "FT4/FT8 QSO fields": "Campi QSO FT4/FT8",
        "My Call": "Mio nominativo",
        "My callsign": "Mio nominativo",
        "My Grid": "Mio locator",
        "My grid": "Mio locator",
        "DX Call": "Nominativo DX",
        "DX callsign": "Nominativo DX",
        "DX Grid": "Locator DX",
        "DX grid": "Locator DX",
        "Generate standard messages": "Genera messaggi standard",
        "Transmit / standard messages": "Trasmissione / messaggi standard",
        "FT4/FT8 controls": "Controlli FT4/FT8",
        "TX first period": "TX primo periodo",
        "TX second period": "TX secondo periodo",
        "Auto sequence": "Sequenza automatica",
        "CQ repeat": "Ripeti CQ",
        "Auto log completed QSOs": "Registra automaticamente i QSO completati",
        "CQ timeout": "Timeout CQ",
        "FT UTC slot clock": "Orologio slot UTC FT",
        "Current period": "Periodo corrente",
        "RX window": "Finestra RX",
        "TX window": "Finestra TX",
        "TX window ends in %1 s": "La finestra TX termina tra %1 s",
        "next TX in %1 s": "prossima TX tra %1 s",
        "Selected TX period": "Periodo TX selezionato",
        "first period": "primo periodo",
        "second period": "secondo periodo",
        "FT8 sequence status": "Stato sequenza FT8",
        "FT8 slot: --": "Slot FT8: --",
        "Sequencer: idle": "Sequencer: inattivo",
        "Sequencer: calling CQ": "Sequencer: chiama CQ",
        "Sequencer: waiting for reply": "Sequencer: attende risposta",
        "Sequencer: sending locator": "Sequencer: invia locator",
        "Sequencer: waiting for report": "Sequencer: attende rapporto",
        "Sequencer: sending report": "Sequencer: invia rapporto",
        "Sequencer: waiting for R-report": "Sequencer: attende rapporto R",
        "Sequencer: sending R-report": "Sequencer: invia rapporto R",
        "Sequencer: waiting for 73/RR73": "Sequencer: attende 73/RR73",
        "Sequencer: sending RR73/73": "Sequencer: invia RR73/73",
        "Sequencer: QSO completed": "Sequencer: QSO completato",
        "CQ repeat: %1 s remaining": "Ripeti CQ: %1 s rimanenti",
        "DX: %1 %2": "DX: %1 %2",
        "Sent %1 / Rcvd %2": "Inviato %1 / Ricevuto %2",
        "FT8 signal report": "Rapporto segnale FT8",
        "Last decoded SNR": "Ultimo SNR decodificato",
        "TX report": "Rapporto TX",
        "FT8 reports are SNR in dB. Send the plain report first; send the R-prefixed report when acknowledging the correspondent's report.": "I rapporti FT8 sono SNR in dB. Invia prima il rapporto semplice; invia il rapporto con prefisso R quando confermi il rapporto del corrispondente.",
        "FT4/FT8 decode diagnostics": "Diagnostica decodifica FT4/FT8",
        "Decode engine": "Motore di decodifica",
        "FT decode engine": "Motore decodifica FT",
        "MSHV classic decoder": "Decoder classico MSHV",
        "Decodium/Raptor enhanced decoder": "Decoder potenziato Decodium/Raptor",
        "Classic keeps the original MSHV-derived single-pass FT8/FT4 receiver. Enhanced enables Raptor-inspired scoring, dedup and multipass subtraction.": "Classico mantiene il ricevitore FT8/FT4 a passata singola derivato da MSHV. Potenziato abilita punteggio, deduplicazione e sottrazione multipass ispirati a Raptor.",
        "FT decode list cleared.": "Lista decodifiche FT cancellata.",
        "Generate/select a CQ message before starting CQ repeat.": "Genera/seleziona un messaggio CQ prima di avviare la ripetizione CQ.",
        "Select or generate an FT8 message before starting TX.": "Seleziona o genera un messaggio FT8 prima di avviare la TX.",
        "NTP status": "Stato NTP",
        "NTP offset": "Offset NTP",
        "NTP RTT / servers": "RTT NTP / server",
        "Last sync": "Ultima sincronizzazione",
        "Time reference": "Riferimento tempo",
        "System clock": "Orologio di sistema",
        "System clock synced; UDP NTP still retrying": "Orologio di sistema sincronizzato; NTP UDP sta ancora riprovando",
        "System clock is not NTP-synchronized": "L'orologio di sistema non è sincronizzato NTP",
        "NTP status unknown; verify PC clock before FT8": "Stato NTP sconosciuto; verifica l'orologio del PC prima di FT8",
        "Decode is close to the next FT8 slot": "La decodifica è vicina allo slot FT8 successivo",
        "Average DT is large; check PC clock or audio timing": "Il DT medio è elevato; controlla l'orologio del PC o il timing audio",
        "Warning": "Avviso",
        "None": "Nessuno",
        "LOCKED": "AGGANCIATO",
        "TRACKING": "INSEGUIMENTO",
        "WAITING": "IN ATTESA",
        "Convergence": "Convergenza",
        "Decode timing": "Timing decodifica",
        "DT correction": "Correzione DT",
        "Last DTs": "Ultimi DT",
        "Per FT8 period": "Per periodo FT8",
        "SC drift comp": "Comp. deriva SC",
        "Slot profiler": "Profilatore slot",
        "Soundcard drift": "Deriva scheda audio",
        "Subtract / dedup drops": "Sottrazione / scarti dedup",
        "Passes / pass-2 candidates": "Passate / candidati passata 2",
        "Search / LDPC": "Ricerca / LDPC",
        "Candidates / decodes": "Candidati / decodifiche",
        "Decodes used": "Decodifiche usate",
        "Last slot": "Ultimo slot",
        "Decode latency": "Latenza decodifica",
        "Waterfall display": "Visualizzazione waterfall",
        "Colour scale": "Scala colori",
        "Palette": "Tavolozza",
        "MadModem / WSJT-X default": "MadModem / WSJT-X predefinita",
        "WSJT-X default": "WSJT-X predefinita",
        "MSHV contrast": "Contrasto MSHV",
        "fldigi colours": "Colori fldigi",
        "Raptor green": "Verde Raptor",
        "Grayscale": "Scala di grigi",
        "Selects the waterfall colour palette. The default palette follows WSJT-X-style weak-signal contrast.": "Seleziona la tavolozza colori della waterfall. La tavolozza predefinita segue il contrasto per segnali deboli in stile WSJT-X.",
        "Display contrast/gamma for the waterfall. Lower values push the noise floor down while strong signals still reach the hot colours.": "Contrasto/gamma della waterfall. Valori più bassi spingono in basso il rumore mentre i segnali forti raggiungono comunque i colori caldi.",
        "Cannot load logbook:": "Impossibile caricare il registro QSO:",
        "Cannot save logbook:": "Impossibile salvare il registro QSO:",
        "Cannot save the current logbook before switching file:": "Impossibile salvare il registro QSO corrente prima di cambiare file:",
        "Logbook file changed:": "File registro QSO cambiato:",
        "Language changed.": "Lingua cambiata.",
        "MM motto": "Motto MM",
        "RX": "RX", "TX": "TX", "Tx": "TX", "Tune": "Sintonia",
        "Auto WPM": "WPM automatico", "Tracked: -- WPM": "Tracciato: -- WPM", "Tracked:": "Tracciato:",
        "Form": "Modulo", "Audio Interface": "Interfaccia audio", "Audio devices": "Dispositivi audio",
        "Audio input": "Ingresso audio", "Audio output": "Uscita audio", "Audio level": "Livello audio",
        "Audio input, audio output and PTT serial port are configured from Settings → Audio / PTT settings.": "Ingresso audio, uscita audio e porta seriale PTT si configurano da Impostazioni → Impostazioni audio / PTT.",
        "From file": "Da file", "From sound card": "Da scheda audio", "From sound card and record": "Da scheda audio e registra", "To sound card": "A scheda audio", "To sound card and record": "A scheda audio e registra",
        "Input Audio Device": "Dispositivo audio di ingresso", "Output Audio Device": "Dispositivo audio di uscita", "Sound Input": "Ingresso audio", "Sound Output": "Uscita audio", "Input  Clock Frequency": "Frequenza clock ingresso", "Output Clock Frequency": "Frequenza clock uscita", "RX Clock": "Clock RX", "TX Clock": "Clock TX", "Swap left and right channel": "Scambia canale sinistro e destro",
        "PTT control": "Controllo PTT", "PTT method": "Metodo PTT", "PTT serial port": "Porta seriale PTT", "PTT tone on other audio channel": "Tono PTT sull'altro canale audio", "TX/PTT": "TX/PTT", "Test PTT": "Test PTT",
        "Receiver status": "Stato ricevitore", "Start RX": "Avvia RX", "Stop RX": "Ferma RX", "Reset image": "Ripristina immagine", "Save PNG": "Salva PNG", "Open WEFAX WAV...": "Apri WAV WEFAX...", "Output folder": "Cartella di uscita",
        "MeteoFax settings": "Impostazioni MeteoFax", "MeteoFax / HF WEFAX RX": "MeteoFax / HF WEFAX RX", "Station": "Stazione", "Slant": "Inclinazione", "Stop wait": "Attesa stop", "Detect stop/end": "Rileva stop/fine", "Tone range band-pass": "Passa-banda gamma toni", "Auto black/white tones": "Toni nero/bianco automatici", "Auto save completed image": "Salva automaticamente immagine completata", "Auto slant": "Inclinazione automatica", "Auto start / phasing": "Avvio/fase automatici", "Auto sync": "Sincronismo automatico", "Black": "Nero", "White": "Bianco", "Max lines": "Righe massime", "Decoder": "Decoder", "Decoder: idle": "Decoder: inattivo", "Idle": "Inattivo",
        "SSTV settings": "Impostazioni SSTV", "SSTV RX": "SSTV RX", "SSTV RX/TX supports Martin, Scottie, Robot and PD families. VIS auto-detect selects the received mode when sync is enabled.": "SSTV RX/TX supporta le famiglie Martin, Scottie, Robot e PD. Il rilevamento automatico VIS seleziona il modo ricevuto quando il sync è abilitato.",
        "Only used for SSTV. This takes several minutes,. Please be patient.": "Usato solo per SSTV. Richiede diversi minuti. Attendere.",
        "Zoom: fit. Mouse wheel zooms, drag pans.": "Zoom: adatta. La rotella zooma, il trascinamento sposta.", "MM ready.": "MM pronto.", "Refresh hidden": "Aggiornamento nascosto", "Fit": "Adatta",
    },
    "fr": {}, "de": {}, "no": {}, "cs": {},
}

# Compact exact maps for the other languages.  They intentionally keep amateur
# radio protocol names/abbreviations in English where that is the normal UI use.
COMMON_TRANSLATIONS = {
    "fr": {
        "About MM": "À propos de MM", "Audio / PTT settings": "Réglages audio / PTT", "Audio / PTT settings...": "Réglages audio / PTT...", "Exit": "Quitter", "+ Logbook...": "+ Journal QSO...", "Logbook": "Journal QSO", "Logbook file settings...": "Réglages du fichier journal QSO...", "Analyze WEFAX WAV...": "Analyser WAV WEFAX...", "Analyze SSTV WAV...": "Analyser WAV SSTV...", "Analyze WAV...": "Analyser WAV...", "CAT / Rig...": "CAT / Radio...", "CAT / Rig control": "Contrôle CAT / radio", "Soundcard calibration...": "Étalonnage carte son...", "Soundcard Calibration": "Étalonnage carte son", "SSTV image editor...": "Éditeur d'image SSTV...", "Open SSTV editor...": "Ouvrir l'éditeur SSTV...", "User/QTH...": "Utilisateur/QTH...", "Text macros...": "Macros texte...", "File": "Fichier", "Settings": "Réglages", "Help": "Aide", "Language": "Langue", "Mode": "Mode", "Status": "État", "Activity": "Activité", "Time": "Heure", "Frequency": "Fréquence", "Freq": "Fréq.", "Message": "Message", "Band": "Bande", "connected": "connecté", "not connected": "non connecté", "Refresh": "Actualiser", "Reset view": "Réinitialiser la vue", "Save map...": "Enregistrer la carte...", "Print map...": "Imprimer la carte...", "QSO map": "Carte QSO", "Show home paths": "Afficher les trajets depuis le QTH", "Show Maidenhead grid": "Afficher la grille Maidenhead", "Overlay 4-character Maidenhead squares; worked squares become green.": "Superpose les carrés Maidenhead à 4 caractères; les carrés contactés deviennent verts.", "Rig / CAT": "Radio / CAT", "CAT: disabled": "CAT : désactivé", "CAT status": "État CAT", "Hamlib: not compiled in": "Hamlib : non compilé", "PTT: serial RTS / none": "PTT : RTS série / aucun", "Stop TX before changing CAT / rig-control settings.": "Arrêtez la TX avant de modifier les réglages CAT / contrôle radio.", "RX audio marker": "Marqueur audio RX", "TX audio marker": "Marqueur audio TX", "Load image...": "Charger une image...", "Send SSTV": "Envoyer SSTV", "Start image TX": "Démarrer TX image", "Stop TX": "Arrêter TX", "STOP": "STOP", "Call": "Indicatif", "Name": "Nom", "Info": "Info", "No SSTV TX image": "Aucune image SSTV TX", "FT4/FT8 activity and QSO control": "Activité FT4/FT8 et contrôle QSO", "Received decodes": "Décodages reçus", "Clear decodes": "Effacer les décodages", "Auto-scroll": "Défilement auto", "QSO activity / RX frequency": "Activité QSO / fréquence RX", "FT4/FT8 QSO fields": "Champs QSO FT4/FT8", "My Call": "Mon indicatif", "My callsign": "Mon indicatif", "My Grid": "Mon locator", "My grid": "Mon locator", "DX Call": "Indicatif DX", "DX callsign": "Indicatif DX", "DX Grid": "Locator DX", "DX grid": "Locator DX", "Generate standard messages": "Générer les messages standard", "Transmit / standard messages": "Émission / messages standard", "FT4/FT8 controls": "Contrôles FT4/FT8", "TX first period": "TX première période", "TX second period": "TX deuxième période", "Auto sequence": "Séquence auto", "CQ repeat": "Répétition CQ", "Auto log completed QSOs": "Journaliser automatiquement les QSO terminés", "CQ timeout": "Délai CQ", "FT UTC slot clock": "Horloge de slot UTC FT", "Current period": "Période actuelle", "RX window": "Fenêtre RX", "TX window": "Fenêtre TX", "TX window ends in %1 s": "La fenêtre TX se termine dans %1 s", "next TX in %1 s": "prochaine TX dans %1 s", "Selected TX period": "Période TX sélectionnée", "first period": "première période", "second period": "deuxième période", "FT8 sequence status": "État de séquence FT8", "FT8 slot: --": "Slot FT8 : --", "Sequencer: idle": "Séquenceur : inactif", "Sequencer: calling CQ": "Séquenceur : appel CQ", "Sequencer: waiting for reply": "Séquenceur : attente réponse", "Sequencer: sending locator": "Séquenceur : envoi locator", "Sequencer: waiting for report": "Séquenceur : attente rapport", "Sequencer: sending report": "Séquenceur : envoi rapport", "Sequencer: waiting for R-report": "Séquenceur : attente rapport R", "Sequencer: sending R-report": "Séquenceur : envoi rapport R", "Sequencer: waiting for 73/RR73": "Séquenceur : attente 73/RR73", "Sequencer: sending RR73/73": "Séquenceur : envoi RR73/73", "Sequencer: QSO completed": "Séquenceur : QSO terminé", "CQ repeat: %1 s remaining": "Répétition CQ : %1 s restantes", "DX: %1 %2": "DX : %1 %2", "Sent %1 / Rcvd %2": "Envoyé %1 / Reçu %2", "FT8 signal report": "Rapport de signal FT8", "Last decoded SNR": "Dernier SNR décodé", "TX report": "Rapport TX", "FT4/FT8 decode diagnostics": "Diagnostics décodage FT4/FT8", "Decode engine": "Moteur de décodage", "FT decode engine": "Moteur de décodage FT", "Waterfall display": "Affichage waterfall", "Colour scale": "Échelle couleur", "Palette": "Palette", "MadModem / WSJT-X default": "MadModem / WSJT-X par défaut", "WSJT-X default": "WSJT-X par défaut", "MSHV contrast": "Contraste MSHV", "fldigi colours": "Couleurs fldigi", "Raptor green": "Vert Raptor", "Grayscale": "Niveaux de gris", "Cannot load logbook:": "Impossible de charger le journal QSO :", "Cannot save logbook:": "Impossible d'enregistrer le journal QSO :", "Language changed.": "Langue modifiée.", "MM motto": "Devise MM", "Tune": "Accord", "Auto WPM": "WPM auto", "Tracked: -- WPM": "Suivi : -- WPM", "Tracked:": "Suivi :", "Form": "Formulaire", "Audio Interface": "Interface audio", "Audio devices": "Périphériques audio", "Audio input": "Entrée audio", "Audio output": "Sortie audio", "Audio level": "Niveau audio", "From file": "Depuis un fichier", "From sound card": "Depuis la carte son", "From sound card and record": "Depuis la carte son et enregistrer", "To sound card": "Vers la carte son", "To sound card and record": "Vers la carte son et enregistrer", "Input Audio Device": "Périphérique audio d'entrée", "Output Audio Device": "Périphérique audio de sortie", "Sound Input": "Entrée son", "Sound Output": "Sortie son", "Input  Clock Frequency": "Fréquence horloge entrée", "Output Clock Frequency": "Fréquence horloge sortie", "RX Clock": "Horloge RX", "TX Clock": "Horloge TX", "Swap left and right channel": "Inverser les canaux gauche/droit", "PTT control": "Contrôle PTT", "PTT method": "Méthode PTT", "PTT serial port": "Port série PTT", "PTT tone on other audio channel": "Tonalité PTT sur l'autre canal audio", "Test PTT": "Tester PTT", "Receiver status": "État du récepteur", "Start RX": "Démarrer RX", "Stop RX": "Arrêter RX", "Reset image": "Réinitialiser image", "Save PNG": "Enregistrer PNG", "Open WEFAX WAV...": "Ouvrir WAV WEFAX...", "Output folder": "Dossier de sortie", "MeteoFax settings": "Réglages MeteoFax", "Station": "Station", "Slant": "Inclinaison", "Stop wait": "Attente stop", "Detect stop/end": "Détecter stop/fin", "Tone range band-pass": "Passe-bande plage de tons", "Auto black/white tones": "Tons noir/blanc auto", "Auto save completed image": "Enregistrer automatiquement l'image terminée", "Auto slant": "Inclinaison auto", "Auto start / phasing": "Démarrage / phasage auto", "Auto sync": "Sync auto", "Black": "Noir", "White": "Blanc", "Max lines": "Lignes max", "Decoder": "Décodeur", "Decoder: idle": "Décodeur : inactif", "Idle": "Inactif", "SSTV settings": "Réglages SSTV", "Only used for SSTV. This takes several minutes,. Please be patient.": "Utilisé seulement pour SSTV. Cela prend plusieurs minutes. Patientez.", "Zoom: fit. Mouse wheel zooms, drag pans.": "Zoom : ajusté. La molette zoome, glisser déplace.", "MM ready.": "MM prêt.", "Fit": "Ajuster", "Refresh hidden": "Actualisation masquée",
    },
    "de": {
        "About MM": "Über MM", "Audio / PTT settings": "Audio-/PTT-Einstellungen", "Audio / PTT settings...": "Audio-/PTT-Einstellungen...", "Exit": "Beenden", "+ Logbook...": "+ QSO-Logbuch...", "Logbook": "QSO-Logbuch", "Logbook file settings...": "Logbuchdatei-Einstellungen...", "Analyze WEFAX WAV...": "WEFAX-WAV analysieren...", "Analyze SSTV WAV...": "SSTV-WAV analysieren...", "Analyze WAV...": "WAV analysieren...", "CAT / Rig...": "CAT / Funkgerät...", "CAT / Rig control": "CAT-/Funkgeräte-Steuerung", "Soundcard calibration...": "Soundkarten-Kalibrierung...", "Soundcard Calibration": "Soundkarten-Kalibrierung", "SSTV image editor...": "SSTV-Bildeditor...", "Open SSTV editor...": "SSTV-Editor öffnen...", "User/QTH...": "Benutzer/QTH...", "Text macros...": "Textmakros...", "File": "Datei", "Settings": "Einstellungen", "Help": "Hilfe", "Language": "Sprache", "Mode": "Modus", "Status": "Status", "Activity": "Aktivität", "Time": "Zeit", "Frequency": "Frequenz", "Freq": "Freq", "Message": "Nachricht", "Band": "Band", "connected": "verbunden", "not connected": "nicht verbunden", "Refresh": "Aktualisieren", "Reset view": "Ansicht zurücksetzen", "Save map...": "Karte speichern...", "Print map...": "Karte drucken...", "QSO map": "QSO-Karte", "Show home paths": "Pfad vom Heimat-QTH zeigen", "Show Maidenhead grid": "Maidenhead-Gitter zeigen", "Overlay 4-character Maidenhead squares; worked squares become green.": "Blendet 4-stellige Maidenhead-Felder ein; gearbeitete Felder werden grün.", "Rig / CAT": "Funkgerät / CAT", "CAT: disabled": "CAT: deaktiviert", "CAT status": "CAT-Status", "Hamlib: not compiled in": "Hamlib: nicht einkompiliert", "PTT: serial RTS / none": "PTT: seriell RTS / keine", "Stop TX before changing CAT / rig-control settings.": "TX vor Änderungen an CAT-/Funkgeräte-Einstellungen stoppen.", "RX audio marker": "RX-Audiomarker", "TX audio marker": "TX-Audiomarker", "Load image...": "Bild laden...", "Send SSTV": "SSTV senden", "Start image TX": "Bild-TX starten", "Stop TX": "TX stoppen", "STOP": "STOP", "Call": "Rufzeichen", "Name": "Name", "Info": "Info", "No SSTV TX image": "Kein SSTV-TX-Bild", "FT4/FT8 activity and QSO control": "FT4/FT8-Aktivität und QSO-Steuerung", "Received decodes": "Empfangene Dekodes", "Clear decodes": "Dekodes löschen", "Auto-scroll": "Auto-Scroll", "QSO activity / RX frequency": "QSO-Aktivität / RX-Frequenz", "FT4/FT8 QSO fields": "FT4/FT8-QSO-Felder", "My Call": "Mein Rufzeichen", "My callsign": "Mein Rufzeichen", "My Grid": "Mein Locator", "My grid": "Mein Locator", "DX Call": "DX-Rufzeichen", "DX callsign": "DX-Rufzeichen", "DX Grid": "DX-Locator", "DX grid": "DX-Locator", "Generate standard messages": "Standardnachrichten erzeugen", "Transmit / standard messages": "Senden / Standardnachrichten", "FT4/FT8 controls": "FT4/FT8-Steuerung", "TX first period": "TX erste Periode", "TX second period": "TX zweite Periode", "Auto sequence": "Auto-Sequenz", "CQ repeat": "CQ-Wiederholung", "Auto log completed QSOs": "Abgeschlossene QSOs automatisch loggen", "CQ timeout": "CQ-Zeitlimit", "FT UTC slot clock": "FT-UTC-Slotuhr", "Current period": "Aktuelle Periode", "RX window": "RX-Fenster", "TX window": "TX-Fenster", "TX window ends in %1 s": "TX-Fenster endet in %1 s", "next TX in %1 s": "nächste TX in %1 s", "Selected TX period": "Gewählte TX-Periode", "first period": "erste Periode", "second period": "zweite Periode", "FT8 sequence status": "FT8-Sequenzstatus", "FT8 slot: --": "FT8-Slot: --", "Sequencer: idle": "Sequencer: inaktiv", "Sequencer: calling CQ": "Sequencer: ruft CQ", "Sequencer: waiting for reply": "Sequencer: wartet auf Antwort", "Sequencer: sending locator": "Sequencer: sendet Locator", "Sequencer: waiting for report": "Sequencer: wartet auf Rapport", "Sequencer: sending report": "Sequencer: sendet Rapport", "Sequencer: waiting for R-report": "Sequencer: wartet auf R-Rapport", "Sequencer: sending R-report": "Sequencer: sendet R-Rapport", "Sequencer: waiting for 73/RR73": "Sequencer: wartet auf 73/RR73", "Sequencer: sending RR73/73": "Sequencer: sendet RR73/73", "Sequencer: QSO completed": "Sequencer: QSO abgeschlossen", "CQ repeat: %1 s remaining": "CQ-Wiederholung: %1 s verbleibend", "DX: %1 %2": "DX: %1 %2", "Sent %1 / Rcvd %2": "Gesendet %1 / Empfangen %2", "FT8 signal report": "FT8-Signalrapport", "Last decoded SNR": "Letzter dekodierter SNR", "TX report": "TX-Rapport", "FT4/FT8 decode diagnostics": "FT4/FT8-Dekodierdiagnose", "Decode engine": "Dekodier-Engine", "FT decode engine": "FT-Dekodier-Engine", "Waterfall display": "Waterfall-Anzeige", "Colour scale": "Farbskala", "Palette": "Palette", "MadModem / WSJT-X default": "MadModem / WSJT-X Standard", "WSJT-X default": "WSJT-X Standard", "MSHV contrast": "MSHV-Kontrast", "fldigi colours": "fldigi-Farben", "Raptor green": "Raptor-Grün", "Grayscale": "Graustufen", "Cannot load logbook:": "Logbuch kann nicht geladen werden:", "Cannot save logbook:": "Logbuch kann nicht gespeichert werden:", "Language changed.": "Sprache geändert.", "MM motto": "MM-Motto", "Tune": "Abstimmen", "Auto WPM": "Auto-WPM", "Tracked: -- WPM": "Verfolgt: -- WPM", "Tracked:": "Verfolgt:", "Form": "Formular", "Audio Interface": "Audioschnittstelle", "Audio devices": "Audiogeräte", "Audio input": "Audioeingang", "Audio output": "Audioausgang", "Audio level": "Audiopegel", "From file": "Aus Datei", "From sound card": "Von Soundkarte", "From sound card and record": "Von Soundkarte und aufnehmen", "To sound card": "Zur Soundkarte", "To sound card and record": "Zur Soundkarte und aufnehmen", "Input Audio Device": "Audio-Eingabegerät", "Output Audio Device": "Audio-Ausgabegerät", "Sound Input": "Toneingang", "Sound Output": "Tonausgang", "Input  Clock Frequency": "Eingangs-Clockfrequenz", "Output Clock Frequency": "Ausgangs-Clockfrequenz", "RX Clock": "RX-Clock", "TX Clock": "TX-Clock", "Swap left and right channel": "Linken und rechten Kanal tauschen", "PTT control": "PTT-Steuerung", "PTT method": "PTT-Methode", "PTT serial port": "PTT-Seriellport", "PTT tone on other audio channel": "PTT-Ton auf anderem Audiokanal", "Test PTT": "PTT testen", "Receiver status": "Empfängerstatus", "Start RX": "RX starten", "Stop RX": "RX stoppen", "Reset image": "Bild zurücksetzen", "Save PNG": "PNG speichern", "Open WEFAX WAV...": "WEFAX-WAV öffnen...", "Output folder": "Ausgabeordner", "MeteoFax settings": "MeteoFax-Einstellungen", "Station": "Station", "Slant": "Schräglage", "Stop wait": "Stop-Wartezeit", "Detect stop/end": "Stop/Ende erkennen", "Tone range band-pass": "Tonbereich-Bandpass", "Auto black/white tones": "Auto Schwarz/Weiß-Töne", "Auto save completed image": "Fertiges Bild automatisch speichern", "Auto slant": "Auto-Schräglage", "Auto start / phasing": "Auto-Start / Phasing", "Auto sync": "Auto-Sync", "Black": "Schwarz", "White": "Weiß", "Max lines": "Max. Zeilen", "Decoder": "Decoder", "Decoder: idle": "Decoder: inaktiv", "Idle": "Inaktiv", "SSTV settings": "SSTV-Einstellungen", "Only used for SSTV. This takes several minutes,. Please be patient.": "Nur für SSTV verwendet. Dies dauert mehrere Minuten. Bitte warten.", "Zoom: fit. Mouse wheel zooms, drag pans.": "Zoom: angepasst. Mausrad zoomt, Ziehen verschiebt.", "MM ready.": "MM bereit.", "Fit": "Einpassen", "Refresh hidden": "Versteckt aktualisieren",
    },
    "no": {
        "About MM": "Om MM", "Audio / PTT settings": "Lyd-/PTT-innstillinger", "Audio / PTT settings...": "Lyd-/PTT-innstillinger...", "Exit": "Avslutt", "+ Logbook...": "+ QSO-logg...", "Logbook": "QSO-logg", "Logbook file settings...": "Innstillinger for loggfil...", "Analyze WEFAX WAV...": "Analyser WEFAX WAV...", "Analyze SSTV WAV...": "Analyser SSTV WAV...", "Analyze WAV...": "Analyser WAV...", "CAT / Rig...": "CAT / Radio...", "CAT / Rig control": "CAT-/radiokontroll", "Soundcard calibration...": "Lydkortkalibrering...", "Soundcard Calibration": "Lydkortkalibrering", "SSTV image editor...": "SSTV-bilderedigering...", "Open SSTV editor...": "Åpne SSTV-redigering...", "User/QTH...": "Bruker/QTH...", "Text macros...": "Tekstmakroer...", "File": "Fil", "Settings": "Innstillinger", "Help": "Hjelp", "Language": "Språk", "Mode": "Modus", "Status": "Status", "Activity": "Aktivitet", "Time": "Tid", "Frequency": "Frekvens", "Freq": "Frekv.", "Message": "Melding", "Band": "Bånd", "connected": "tilkoblet", "not connected": "ikke tilkoblet", "Refresh": "Oppdater", "Reset view": "Tilbakestill visning", "Save map...": "Lagre kart...", "Print map...": "Skriv ut kart...", "QSO map": "QSO-kart", "Show home paths": "Vis hjemmebaner", "Show Maidenhead grid": "Vis Maidenhead-rutenett", "Overlay 4-character Maidenhead squares; worked squares become green.": "Legger over 4-tegns Maidenhead-ruter; kjørte ruter blir grønne.", "Rig / CAT": "Radio / CAT", "CAT: disabled": "CAT: deaktivert", "CAT status": "CAT-status", "Hamlib: not compiled in": "Hamlib: ikke kompilert inn", "PTT: serial RTS / none": "PTT: seriell RTS / ingen", "Stop TX before changing CAT / rig-control settings.": "Stopp TX før du endrer CAT-/radioinnstillinger.", "RX audio marker": "RX-lydmarkør", "TX audio marker": "TX-lydmarkør", "Load image...": "Last bilde...", "Send SSTV": "Send SSTV", "Start image TX": "Start bilde-TX", "Stop TX": "Stopp TX", "STOP": "STOPP", "Call": "Kallesignal", "Name": "Navn", "Info": "Info", "No SSTV TX image": "Ingen SSTV TX-bilde", "FT4/FT8 activity and QSO control": "FT4/FT8-aktivitet og QSO-kontroll", "Received decodes": "Mottatte dekodinger", "Clear decodes": "Tøm dekodinger", "Auto-scroll": "Autorulling", "QSO activity / RX frequency": "QSO-aktivitet / RX-frekvens", "FT4/FT8 QSO fields": "FT4/FT8 QSO-felt", "My Call": "Mitt kallesignal", "My callsign": "Mitt kallesignal", "My Grid": "Min lokator", "My grid": "Min lokator", "DX Call": "DX-kallesignal", "DX callsign": "DX-kallesignal", "DX Grid": "DX-lokator", "DX grid": "DX-lokator", "Generate standard messages": "Generer standardmeldinger", "Transmit / standard messages": "Sending / standardmeldinger", "FT4/FT8 controls": "FT4/FT8-kontroller", "TX first period": "TX første periode", "TX second period": "TX andre periode", "Auto sequence": "Autosekvens", "CQ repeat": "CQ-gjentakelse", "Auto log completed QSOs": "Logg fullførte QSO-er automatisk", "CQ timeout": "CQ-tidsavbrudd", "FT UTC slot clock": "FT UTC-slotklokke", "Current period": "Gjeldende periode", "RX window": "RX-vindu", "TX window": "TX-vindu", "TX window ends in %1 s": "TX-vindu slutter om %1 s", "next TX in %1 s": "neste TX om %1 s", "Selected TX period": "Valgt TX-periode", "first period": "første periode", "second period": "andre periode", "FT8 sequence status": "FT8-sekvensstatus", "FT8 slot: --": "FT8-slot: --", "Sequencer: idle": "Sekvenser: inaktiv", "Sequencer: calling CQ": "Sekvenser: kaller CQ", "Sequencer: waiting for reply": "Sekvenser: venter på svar", "Sequencer: sending locator": "Sekvenser: sender lokator", "Sequencer: waiting for report": "Sekvenser: venter på rapport", "Sequencer: sending report": "Sekvenser: sender rapport", "Sequencer: waiting for R-report": "Sekvenser: venter på R-rapport", "Sequencer: sending R-report": "Sekvenser: sender R-rapport", "Sequencer: waiting for 73/RR73": "Sekvenser: venter på 73/RR73", "Sequencer: sending RR73/73": "Sekvenser: sender RR73/73", "Sequencer: QSO completed": "Sekvenser: QSO fullført", "CQ repeat: %1 s remaining": "CQ-gjentakelse: %1 s igjen", "DX: %1 %2": "DX: %1 %2", "Sent %1 / Rcvd %2": "Sendt %1 / Mottatt %2", "FT8 signal report": "FT8-signalrapport", "Last decoded SNR": "Siste dekodede SNR", "TX report": "TX-rapport", "FT4/FT8 decode diagnostics": "FT4/FT8-dekodediagnostikk", "Decode engine": "Dekodemotor", "FT decode engine": "FT-dekodemotor", "Waterfall display": "Waterfall-visning", "Colour scale": "Fargeskala", "Palette": "Palett", "MadModem / WSJT-X default": "MadModem / WSJT-X standard", "WSJT-X default": "WSJT-X standard", "MSHV contrast": "MSHV-kontrast", "fldigi colours": "fldigi-farger", "Raptor green": "Raptor-grønn", "Grayscale": "Gråskala", "Cannot load logbook:": "Kan ikke laste QSO-logg:", "Cannot save logbook:": "Kan ikke lagre QSO-logg:", "Language changed.": "Språk endret.", "MM motto": "MM-motto", "Tune": "Tune", "Auto WPM": "Auto WPM", "Tracked: -- WPM": "Sporer: -- WPM", "Tracked:": "Sporer:", "Form": "Skjema", "Audio Interface": "Lydgrensesnitt", "Audio devices": "Lydenheter", "Audio input": "Lydinngang", "Audio output": "Lydutgang", "Audio level": "Lydnivå", "From file": "Fra fil", "From sound card": "Fra lydkort", "From sound card and record": "Fra lydkort og ta opp", "To sound card": "Til lydkort", "To sound card and record": "Til lydkort og ta opp", "Input Audio Device": "Lydinngangsenhet", "Output Audio Device": "Lydutgangsenhet", "Sound Input": "Lydinngang", "Sound Output": "Lydutgang", "Input  Clock Frequency": "Inngangs-klokkefrekvens", "Output Clock Frequency": "Utgangs-klokkefrekvens", "RX Clock": "RX-klokke", "TX Clock": "TX-klokke", "Swap left and right channel": "Bytt venstre og høyre kanal", "PTT control": "PTT-kontroll", "PTT method": "PTT-metode", "PTT serial port": "PTT-seriellport", "PTT tone on other audio channel": "PTT-tone på annen lydkanal", "Test PTT": "Test PTT", "Receiver status": "Mottakerstatus", "Start RX": "Start RX", "Stop RX": "Stopp RX", "Reset image": "Tilbakestill bilde", "Save PNG": "Lagre PNG", "Open WEFAX WAV...": "Åpne WEFAX WAV...", "Output folder": "Utmappe", "MeteoFax settings": "MeteoFax-innstillinger", "Station": "Stasjon", "Slant": "Skråstilling", "Stop wait": "Stoppventing", "Detect stop/end": "Oppdag stopp/slutt", "Tone range band-pass": "Toneområde-båndpass", "Auto black/white tones": "Auto svart/hvitt-toner", "Auto save completed image": "Autolagre fullført bilde", "Auto slant": "Auto skråstilling", "Auto start / phasing": "Auto start / fase", "Auto sync": "Auto sync", "Black": "Svart", "White": "Hvit", "Max lines": "Maks linjer", "Decoder": "Dekoder", "Decoder: idle": "Dekoder: inaktiv", "Idle": "Inaktiv", "SSTV settings": "SSTV-innstillinger", "Only used for SSTV. This takes several minutes,. Please be patient.": "Brukes bare for SSTV. Dette tar flere minutter. Vær tålmodig.", "Zoom: fit. Mouse wheel zooms, drag pans.": "Zoom: tilpass. Musehjul zoomer, dra panorerer.", "MM ready.": "MM klar.", "Fit": "Tilpass", "Refresh hidden": "Oppdater skjulte",
    },
    "cs": {
        "About MM": "O MM", "Audio / PTT settings": "Nastavení zvuku / PTT", "Audio / PTT settings...": "Nastavení zvuku / PTT...", "Exit": "Konec", "+ Logbook...": "+ QSO deník...", "Logbook": "QSO deník", "Logbook file settings...": "Nastavení souboru QSO deníku...", "Analyze WEFAX WAV...": "Analyzovat WEFAX WAV...", "Analyze SSTV WAV...": "Analyzovat SSTV WAV...", "Analyze WAV...": "Analyzovat WAV...", "CAT / Rig...": "CAT / Rádio...", "CAT / Rig control": "Ovládání CAT / rádia", "Soundcard calibration...": "Kalibrace zvukové karty...", "Soundcard Calibration": "Kalibrace zvukové karty", "SSTV image editor...": "Editor obrázků SSTV...", "Open SSTV editor...": "Otevřít editor SSTV...", "User/QTH...": "Uživatel/QTH...", "Text macros...": "Textová makra...", "File": "Soubor", "Settings": "Nastavení", "Help": "Nápověda", "Language": "Jazyk", "Mode": "Režim", "Status": "Stav", "Activity": "Aktivita", "Time": "Čas", "Frequency": "Frekvence", "Freq": "Frekv.", "Message": "Zpráva", "Band": "Pásmo", "connected": "připojeno", "not connected": "nepřipojeno", "Refresh": "Obnovit", "Reset view": "Obnovit pohled", "Save map...": "Uložit mapu...", "Print map...": "Tisk mapy...", "QSO map": "Mapa QSO", "Show home paths": "Zobrazit trasy z QTH", "Show Maidenhead grid": "Zobrazit mřížku Maidenhead", "Overlay 4-character Maidenhead squares; worked squares become green.": "Překryje 4znaková pole Maidenhead; uskutečněná pole zezelenají.", "Rig / CAT": "Rádio / CAT", "CAT: disabled": "CAT: vypnuto", "CAT status": "Stav CAT", "Hamlib: not compiled in": "Hamlib: není zkompilován", "PTT: serial RTS / none": "PTT: sériové RTS / žádné", "Stop TX before changing CAT / rig-control settings.": "Před změnou nastavení CAT / ovládání rádia zastavte TX.", "RX audio marker": "Zvuková značka RX", "TX audio marker": "Zvuková značka TX", "Load image...": "Načíst obrázek...", "Send SSTV": "Odeslat SSTV", "Start image TX": "Spustit TX obrázku", "Stop TX": "Zastavit TX", "STOP": "STOP", "Call": "Značka", "Name": "Jméno", "Info": "Info", "No SSTV TX image": "Žádný SSTV TX obrázek", "FT4/FT8 activity and QSO control": "Aktivita FT4/FT8 a řízení QSO", "Received decodes": "Přijaté dekódy", "Clear decodes": "Vymazat dekódy", "Auto-scroll": "Automatický posuv", "QSO activity / RX frequency": "Aktivita QSO / frekvence RX", "FT4/FT8 QSO fields": "Pole QSO FT4/FT8", "My Call": "Moje značka", "My callsign": "Moje značka", "My Grid": "Můj locator", "My grid": "Můj locator", "DX Call": "DX značka", "DX callsign": "DX značka", "DX Grid": "DX locator", "DX grid": "DX locator", "Generate standard messages": "Generovat standardní zprávy", "Transmit / standard messages": "Vysílání / standardní zprávy", "FT4/FT8 controls": "Ovládání FT4/FT8", "TX first period": "TX první perioda", "TX second period": "TX druhá perioda", "Auto sequence": "Automatická sekvence", "CQ repeat": "Opakovat CQ", "Auto log completed QSOs": "Automaticky zapsat dokončená QSO", "CQ timeout": "Časový limit CQ", "FT UTC slot clock": "Hodiny FT UTC slotu", "Current period": "Aktuální perioda", "RX window": "Okno RX", "TX window": "Okno TX", "TX window ends in %1 s": "Okno TX končí za %1 s", "next TX in %1 s": "další TX za %1 s", "Selected TX period": "Vybraná TX perioda", "first period": "první perioda", "second period": "druhá perioda", "FT8 sequence status": "Stav sekvence FT8", "FT8 slot: --": "FT8 slot: --", "Sequencer: idle": "Sekvencer: nečinný", "Sequencer: calling CQ": "Sekvencer: volá CQ", "Sequencer: waiting for reply": "Sekvencer: čeká na odpověď", "Sequencer: sending locator": "Sekvencer: odesílá locator", "Sequencer: waiting for report": "Sekvencer: čeká na report", "Sequencer: sending report": "Sekvencer: odesílá report", "Sequencer: waiting for R-report": "Sekvencer: čeká na R-report", "Sequencer: sending R-report": "Sekvencer: odesílá R-report", "Sequencer: waiting for 73/RR73": "Sekvencer: čeká na 73/RR73", "Sequencer: sending RR73/73": "Sekvencer: odesílá RR73/73", "Sequencer: QSO completed": "Sekvencer: QSO dokončeno", "CQ repeat: %1 s remaining": "Opakování CQ: zbývá %1 s", "DX: %1 %2": "DX: %1 %2", "Sent %1 / Rcvd %2": "Odesláno %1 / Přijato %2", "FT8 signal report": "Report signálu FT8", "Last decoded SNR": "Poslední dekódované SNR", "TX report": "TX report", "FT4/FT8 decode diagnostics": "Diagnostika dekódování FT4/FT8", "Decode engine": "Dekódovací engine", "FT decode engine": "FT dekódovací engine", "Waterfall display": "Zobrazení waterfall", "Colour scale": "Barevná škála", "Palette": "Paleta", "MadModem / WSJT-X default": "MadModem / WSJT-X výchozí", "WSJT-X default": "WSJT-X výchozí", "MSHV contrast": "Kontrast MSHV", "fldigi colours": "Barvy fldigi", "Raptor green": "Raptor zelená", "Grayscale": "Stupně šedi", "Cannot load logbook:": "Nelze načíst QSO deník:", "Cannot save logbook:": "Nelze uložit QSO deník:", "Language changed.": "Jazyk změněn.", "MM motto": "Motto MM", "Tune": "Ladit", "Auto WPM": "Auto WPM", "Tracked: -- WPM": "Sledováno: -- WPM", "Tracked:": "Sledováno:", "Form": "Formulář", "Audio Interface": "Zvukové rozhraní", "Audio devices": "Zvuková zařízení", "Audio input": "Zvukový vstup", "Audio output": "Zvukový výstup", "Audio level": "Úroveň zvuku", "From file": "Ze souboru", "From sound card": "Ze zvukové karty", "From sound card and record": "Ze zvukové karty a nahrávat", "To sound card": "Do zvukové karty", "To sound card and record": "Do zvukové karty a nahrávat", "Input Audio Device": "Vstupní zvukové zařízení", "Output Audio Device": "Výstupní zvukové zařízení", "Sound Input": "Zvukový vstup", "Sound Output": "Zvukový výstup", "Input  Clock Frequency": "Frekvence vstupních hodin", "Output Clock Frequency": "Frekvence výstupních hodin", "RX Clock": "RX hodiny", "TX Clock": "TX hodiny", "Swap left and right channel": "Prohodit levý a pravý kanál", "PTT control": "Ovládání PTT", "PTT method": "Metoda PTT", "PTT serial port": "Sériový port PTT", "PTT tone on other audio channel": "PTT tón na druhém audio kanálu", "Test PTT": "Test PTT", "Receiver status": "Stav přijímače", "Start RX": "Spustit RX", "Stop RX": "Zastavit RX", "Reset image": "Resetovat obrázek", "Save PNG": "Uložit PNG", "Open WEFAX WAV...": "Otevřít WEFAX WAV...", "Output folder": "Výstupní složka", "MeteoFax settings": "Nastavení MeteoFax", "Station": "Stanice", "Slant": "Sklon", "Stop wait": "Čekání na stop", "Detect stop/end": "Detekovat stop/konec", "Tone range band-pass": "Pásmová propust rozsahu tónů", "Auto black/white tones": "Auto černé/bílé tóny", "Auto save completed image": "Automaticky uložit dokončený obrázek", "Auto slant": "Auto sklon", "Auto start / phasing": "Auto start / fázování", "Auto sync": "Auto sync", "Black": "Černá", "White": "Bílá", "Max lines": "Max. řádků", "Decoder": "Dekodér", "Decoder: idle": "Dekodér: nečinný", "Idle": "Nečinný", "SSTV settings": "Nastavení SSTV", "Only used for SSTV. This takes several minutes,. Please be patient.": "Používá se pouze pro SSTV. Trvá to několik minut. Prosím čekejte.", "Zoom: fit. Mouse wheel zooms, drag pans.": "Zoom: přizpůsobit. Kolečko zoomuje, tažení posouvá.", "MM ready.": "MM připraven.", "Fit": "Přizpůsobit", "Refresh hidden": "Obnovit skryté",
    },
}
EXACT.update(COMMON_TRANSLATIONS)

# Terms used only when no exact phrase is available.  This is deliberately
# conservative; protocol words and abbreviations remain recognizable.
TERMS = {
    "it": [("settings", "impostazioni"), ("Settings", "Impostazioni"), ("failed", "fallito"), ("Failed", "Fallito"), ("error", "errore"), ("Error", "Errore"), ("image", "immagine"), ("Image", "Immagine"), ("load", "carica"), ("Load", "Carica"), ("save", "salva"), ("Save", "Salva"), ("open", "apri"), ("Open", "Apri"), ("start", "avvia"), ("Start", "Avvia"), ("stop", "ferma"), ("Stop", "Ferma"), ("input", "ingresso"), ("Input", "Ingresso"), ("output", "uscita"), ("Output", "Uscita"), ("black", "nero"), ("Black", "Nero"), ("white", "bianco"), ("White", "Bianco"), ("frequency", "frequenza"), ("Frequency", "Frequenza"), ("level", "livello"), ("Level", "Livello"), ("window", "finestra"), ("Window", "Finestra"), ("decoder", "decoder"), ("Decoder", "Decoder"), ("completed", "completato"), ("Completed", "Completato"), ("waiting", "in attesa"), ("Waiting", "In attesa"), ("report", "rapporto"), ("Report", "Rapporto")],
    "fr": [("settings", "réglages"), ("Settings", "Réglages"), ("failed", "échoué"), ("Failed", "Échoué"), ("error", "erreur"), ("Error", "Erreur"), ("image", "image"), ("Image", "Image"), ("load", "charger"), ("Load", "Charger"), ("save", "enregistrer"), ("Save", "Enregistrer"), ("open", "ouvrir"), ("Open", "Ouvrir"), ("start", "démarrer"), ("Start", "Démarrer"), ("stop", "arrêter"), ("Stop", "Arrêter"), ("input", "entrée"), ("Input", "Entrée"), ("output", "sortie"), ("Output", "Sortie"), ("black", "noir"), ("Black", "Noir"), ("white", "blanc"), ("White", "Blanc"), ("frequency", "fréquence"), ("Frequency", "Fréquence"), ("level", "niveau"), ("Level", "Niveau"), ("window", "fenêtre"), ("Window", "Fenêtre"), ("completed", "terminé"), ("Completed", "Terminé"), ("waiting", "en attente"), ("Waiting", "En attente"), ("report", "rapport"), ("Report", "Rapport")],
    "de": [("settings", "Einstellungen"), ("Settings", "Einstellungen"), ("failed", "fehlgeschlagen"), ("Failed", "Fehlgeschlagen"), ("error", "Fehler"), ("Error", "Fehler"), ("image", "Bild"), ("Image", "Bild"), ("load", "laden"), ("Load", "Laden"), ("save", "speichern"), ("Save", "Speichern"), ("open", "öffnen"), ("Open", "Öffnen"), ("start", "starten"), ("Start", "Starten"), ("stop", "stoppen"), ("Stop", "Stoppen"), ("input", "Eingang"), ("Input", "Eingang"), ("output", "Ausgang"), ("Output", "Ausgang"), ("black", "schwarz"), ("Black", "Schwarz"), ("white", "weiß"), ("White", "Weiß"), ("frequency", "Frequenz"), ("Frequency", "Frequenz"), ("level", "Pegel"), ("Level", "Pegel"), ("window", "Fenster"), ("Window", "Fenster"), ("completed", "abgeschlossen"), ("Completed", "Abgeschlossen"), ("waiting", "wartet"), ("Waiting", "Wartet"), ("report", "Rapport"), ("Report", "Rapport")],
    "no": [("settings", "innstillinger"), ("Settings", "Innstillinger"), ("failed", "mislyktes"), ("Failed", "Mislyktes"), ("error", "feil"), ("Error", "Feil"), ("image", "bilde"), ("Image", "Bilde"), ("load", "last"), ("Load", "Last"), ("save", "lagre"), ("Save", "Lagre"), ("open", "åpne"), ("Open", "Åpne"), ("start", "start"), ("Start", "Start"), ("stop", "stopp"), ("Stop", "Stopp"), ("input", "inngang"), ("Input", "Inngang"), ("output", "utgang"), ("Output", "Utgang"), ("black", "svart"), ("Black", "Svart"), ("white", "hvit"), ("White", "Hvit"), ("frequency", "frekvens"), ("Frequency", "Frekvens"), ("level", "nivå"), ("Level", "Nivå"), ("window", "vindu"), ("Window", "Vindu"), ("completed", "fullført"), ("Completed", "Fullført"), ("waiting", "venter"), ("Waiting", "Venter"), ("report", "rapport"), ("Report", "Rapport")],
    "cs": [("settings", "nastavení"), ("Settings", "Nastavení"), ("failed", "selhalo"), ("Failed", "Selhalo"), ("error", "chyba"), ("Error", "Chyba"), ("image", "obrázek"), ("Image", "Obrázek"), ("load", "načíst"), ("Load", "Načíst"), ("save", "uložit"), ("Save", "Uložit"), ("open", "otevřít"), ("Open", "Otevřít"), ("start", "spustit"), ("Start", "Spustit"), ("stop", "zastavit"), ("Stop", "Zastavit"), ("input", "vstup"), ("Input", "Vstup"), ("output", "výstup"), ("Output", "Výstup"), ("black", "černá"), ("Black", "Černá"), ("white", "bílá"), ("White", "Bílá"), ("frequency", "frekvence"), ("Frequency", "Frekvence"), ("level", "úroveň"), ("Level", "Úroveň"), ("window", "okno"), ("Window", "Okno"), ("completed", "dokončeno"), ("Completed", "Dokončeno"), ("waiting", "čeká"), ("Waiting", "Čeká"), ("report", "report"), ("Report", "Report")],
}

TECH_RE = re.compile(r"^(?:[#0-9A-Z_./:+\-%(), ]|Hz|kHz|MHz|dB|WPM|LPM|IOC|RTTY|SSTV|WEFAX|FT4|FT8|CW|PTT|CAT|QSO|QTH|RX|TX|AFSK|USB|LSB|NOAA|USCG|DWD|JMH|VMC|VMW|NMF|NMC|GYA|DDH3|DDK3|DDK6)+$")




# Second-pass curated translations for dialog/message-box text that is generated
# from local L("source") calls or extracted from .ui forms.  Technical tokens
# (ADIF, CAT, PTT, FT8, WEFAX, callsigns, units) are intentionally preserved.
COMMON_EXACT = {
    "it": {
        "MadModem logbook": "Registro QSO MadModem",
        "Advanced search": "Ricerca avanzata",
        "Any field: callsign, grid, band, mode, report or UTC date...": "Qualsiasi campo: nominativo, locator, banda, modo, rapporto o data UTC...",
        "From UTC": "Da UTC",
        "To UTC": "A UTC",
        "Clear search": "Cancella ricerca",
        "Any": "Qualsiasi",
        "Callsign": "Nominativo",
        "RST sent": "RST inviato",
        "RST rcvd": "RST ricevuto",
        "Import ADIF...": "Importa ADIF...",
        "Export all...": "Esporta tutto...",
        "Export result...": "Esporta risultato...",
        "Export selected...": "Esporta selezionati...",
        "Delete selected": "Elimina selezionati",
        "Delete the selected QSO records from the ADIF logbook after confirmation.": "Elimina dal registro ADIF i QSO selezionati dopo conferma.",
        "Print...": "Stampa...",
        "Save PDF...": "Salva PDF...",
        "Close": "Chiudi",
        "Import ADIF": "Importa ADIF",
        "Import failed:": "Importazione fallita:",
        "Imported %1 QSO records.": "Importati %1 record QSO.",
        "No QSO records to export.": "Nessun record QSO da esportare.",
        "Export failed:": "Esportazione fallita:",
        "Delete selected QSOs": "Elimina QSO selezionati",
        "Select one or more QSO records to delete.": "Seleziona uno o più record QSO da eliminare.",
        "Delete failed:": "Eliminazione fallita:",
        "No matching QSO records were removed.": "Nessun record QSO corrispondente è stato rimosso.",
        "Deleted %1 QSO record(s).": "Eliminati %1 record QSO.",
        "Print logbook": "Stampa registro QSO",
        "No QSO records to print.": "Nessun record QSO da stampare.",
        "Print MadModem logbook": "Stampa registro QSO MadModem",
        "Save logbook PDF": "Salva PDF del registro QSO",
        "No QSO records to save.": "Nessun record QSO da salvare.",
        "Logbook file settings": "Impostazioni file registro QSO",
        "MadModem keeps the internal logbook as one ADIF file. Choose where that file is stored. The default path is beside the application executable.": "MadModem conserva il registro interno in un unico file ADIF. Scegli dove salvarlo. Il percorso predefinito è accanto all'eseguibile dell'applicazione.",
        "Logbook file": "File registro QSO",
        "Default path": "Percorso predefinito",
        "Browse...": "Sfoglia...",
        "Use default path": "Usa percorso predefinito",
        "OK": "OK",
        "Cancel": "Annulla",
        "Select logbook ADIF file": "Seleziona file ADIF del registro",
        "ADIF files (*.adi *.adif);;All files (*)": "File ADIF (*.adi *.adif);;Tutti i file (*)",
        "Please choose a logbook ADIF file path.": "Scegli un percorso per il file ADIF del registro.",
        "The folder does not exist yet. MadModem will try to create it when saving the logbook.": "La cartella non esiste ancora. MadModem proverà a crearla durante il salvataggio del registro.",
        "Please include a file name, for example logbook.adi.": "Inserisci anche un nome file, per esempio logbook.adi.",
        "Hamlib available": "Hamlib disponibile",
        "Hamlib not compiled in": "Hamlib non compilato",
        "radio models:": "modelli radio:",
        "Use CAT PTT for transmit": "Usa CAT PTT per la trasmissione",
        "Radio maker": "Produttore radio",
        "Filter models": "Filtra modelli",
        "Type part of the model name, e.g. 7300, FT-991, TS-590": "Digita parte del modello, es. 7300, FT-991, TS-590",
        "Radio model": "Modello radio",
        "Custom Hamlib model ID": "ID modello Hamlib personalizzato",
        "TX audio / PTT route": "Percorso audio TX / PTT",
        "Radio default / microphone CAT PTT": "Predefinito radio / microfono CAT PTT",
        "Digital DATA PTT only": "Solo PTT DATA digitale",
        "Force DATA/USB mode + DATA PTT": "Forza modo DATA/USB + DATA PTT",
        "CAT serial port": "Porta seriale CAT",
        "CAT TCP address": "Indirizzo TCP CAT",
        "Optional: host:port, rigctld:host:port or HRD localhost:7809; leave empty for serial CAT": "Opzionale: host:porta, rigctld:host:porta o HRD localhost:7809; lascia vuoto per CAT seriale",
        "Serial speed": "Velocità seriale",
        "Data bits": "Bit dati",
        "Stop bits": "Bit di stop",
        "Handshake": "Handshake",
        "Default / unchanged": "Predefinito / invariato",
        "None": "Nessuno",
        "Hardware RTS/CTS": "Hardware RTS/CTS",
        "Force DTR": "Forza DTR",
        "Unchanged": "Invariato",
        "Force low/OFF": "Forza basso/OFF",
        "Force high/ON": "Forza alto/ON",
        "Force RTS": "Forza RTS",
        "None / audio only": "Nessuno / solo audio",
        "CAT / Hamlib": "CAT / Hamlib",
        "Serial RTS": "RTS seriale",
        "Serial DTR": "DTR seriale",
        "Poll interval": "Intervallo polling",
        "Test CAT": "Test CAT",
        "Test TX": "Test TX",
        "Force RX": "Forza RX",
        "CAT test not run yet.": "Test CAT non ancora eseguito.",
        "Confirm PTT test": "Conferma test PTT",
        "This test will intentionally switch the radio to TX for a very short time, then force RX. Continue?": "Questo test porterà intenzionalmente la radio in TX per pochissimo tempo, poi forzerà RX. Continuare?",
        "PTT TX test cancelled — no TX command sent.": "Test PTT TX annullato — nessun comando TX inviato.",
        "Testing CAT PTT TX...": "Test CAT PTT TX...",
        "Sending CAT PTT OFF / RX...": "Invio CAT PTT OFF / RX...",
        "Force WEFAX RX now": "Forza RX WEFAX ora",
        "Force SSTV RX now": "Forza RX SSTV ora",
        "Runtime log": "Log runtime",
        "RX monitor — no FT TX armed": "Monitor RX — nessuna TX FT armata",
        "FT activity": "Attività FT",
        "MSHV-derived native decoder": "Decoder nativo derivato da MSHV",
        "FT decoder": "Decoder FT",
        "The arrow marks the standard message currently selected or armed by the FT auto-sequencer.": "La freccia indica il messaggio standard selezionato o armato dall'auto-sequencer FT.",
        "Station identity required": "Identità stazione richiesta",
        "ON AIR NOW": "IN TX ORA",
        "ARMED NEXT TX": "ARMATO PROSSIMA TX",
        "RX MONITOR": "MONITOR RX",
        "last TX": "ultima TX",
        "FT WAV analysis": "Analisi WAV FT",
        "Select FT8 or FT4 before analyzing an FT WAV file.": "Seleziona FT8 o FT4 prima di analizzare un file WAV FT.",
        "WAV audio (*.wav *.wave);;All files (*)": "Audio WAV (*.wav *.wave);;Tutti i file (*)",
        "Ready": "Pronto",
        "Clear": "Cancella",
    },
    "fr": {
        "MadModem logbook": "Journal QSO MadModem", "Advanced search": "Recherche avancée", "From UTC": "Depuis UTC", "To UTC": "Jusqu'à UTC", "Clear search": "Effacer la recherche", "Any": "Tout", "Callsign": "Indicatif", "RST sent": "RST envoyé", "RST rcvd": "RST reçu", "Import ADIF...": "Importer ADIF...", "Export all...": "Tout exporter...", "Export result...": "Exporter le résultat...", "Export selected...": "Exporter la sélection...", "Delete selected": "Supprimer la sélection", "Print...": "Imprimer...", "Save PDF...": "Enregistrer PDF...", "Close": "Fermer", "Import failed:": "Échec de l'importation :", "Imported %1 QSO records.": "%1 QSO importés.", "No QSO records to export.": "Aucun QSO à exporter.", "Export failed:": "Échec de l'exportation :", "Delete selected QSOs": "Supprimer les QSO sélectionnés", "Select one or more QSO records to delete.": "Sélectionnez un ou plusieurs QSO à supprimer.", "Delete failed:": "Échec de la suppression :", "No matching QSO records were removed.": "Aucun QSO correspondant n'a été supprimé.", "Deleted %1 QSO record(s).": "%1 QSO supprimés.", "Print logbook": "Imprimer le journal QSO", "No QSO records to print.": "Aucun QSO à imprimer.", "Print MadModem logbook": "Imprimer le journal QSO MadModem", "Save logbook PDF": "Enregistrer le journal QSO en PDF", "No QSO records to save.": "Aucun QSO à enregistrer.", "Logbook file settings": "Réglages du fichier journal QSO", "Logbook file": "Fichier journal QSO", "Default path": "Chemin par défaut", "Browse...": "Parcourir...", "Use default path": "Utiliser le chemin par défaut", "OK": "OK", "Cancel": "Annuler", "Please choose a logbook ADIF file path.": "Choisissez un chemin de fichier ADIF pour le journal.", "Hamlib available": "Hamlib disponible", "Hamlib not compiled in": "Hamlib non compilé", "Use CAT PTT for transmit": "Utiliser CAT PTT pour transmettre", "Radio maker": "Fabricant radio", "Filter models": "Filtrer les modèles", "Radio model": "Modèle radio", "TX audio / PTT route": "Route audio TX / PTT", "CAT serial port": "Port série CAT", "CAT TCP address": "Adresse TCP CAT", "Serial speed": "Vitesse série", "Data bits": "Bits de données", "Stop bits": "Bits d'arrêt", "None": "Aucun", "Unchanged": "Inchangé", "Force low/OFF": "Forcer bas/OFF", "Force high/ON": "Forcer haut/ON", "None / audio only": "Aucun / audio seulement", "Serial RTS": "RTS série", "Serial DTR": "DTR série", "Poll interval": "Intervalle de polling", "Test CAT": "Test CAT", "Test TX": "Test TX", "Force RX": "Forcer RX", "Confirm PTT test": "Confirmer le test PTT", "Runtime log": "Journal d'exécution", "Ready": "Prêt", "Clear": "Effacer", "Force WEFAX RX now": "Forcer RX WEFAX maintenant", "Force SSTV RX now": "Forcer RX SSTV maintenant", "FT activity": "Activité FT", "FT decoder": "Décodeur FT", "Station identity required": "Identité station requise", "RX monitor — no FT TX armed": "Moniteur RX — aucune TX FT armée", "ON AIR NOW": "EN ÉMISSION", "ARMED NEXT TX": "ARMÉ PROCHAINE TX", "RX MONITOR": "MONITEUR RX", "last TX": "dernière TX", "FT WAV analysis": "Analyse WAV FT", "Ready": "Prêt"
    },
    "de": {
        "MadModem logbook": "MadModem-QSO-Logbuch", "Advanced search": "Erweiterte Suche", "From UTC": "Von UTC", "To UTC": "Bis UTC", "Clear search": "Suche löschen", "Any": "Beliebig", "Callsign": "Rufzeichen", "RST sent": "RST gesendet", "RST rcvd": "RST empfangen", "Import ADIF...": "ADIF importieren...", "Export all...": "Alles exportieren...", "Export result...": "Ergebnis exportieren...", "Export selected...": "Auswahl exportieren...", "Delete selected": "Auswahl löschen", "Print...": "Drucken...", "Save PDF...": "PDF speichern...", "Close": "Schließen", "Import failed:": "Import fehlgeschlagen:", "Imported %1 QSO records.": "%1 QSO-Datensätze importiert.", "No QSO records to export.": "Keine QSO-Datensätze zum Exportieren.", "Export failed:": "Export fehlgeschlagen:", "Delete selected QSOs": "Ausgewählte QSOs löschen", "Select one or more QSO records to delete.": "Einen oder mehrere QSO-Datensätze zum Löschen auswählen.", "Delete failed:": "Löschen fehlgeschlagen:", "No matching QSO records were removed.": "Keine passenden QSO-Datensätze wurden entfernt.", "Deleted %1 QSO record(s).": "%1 QSO-Datensätze gelöscht.", "Print logbook": "Logbuch drucken", "No QSO records to print.": "Keine QSO-Datensätze zum Drucken.", "Print MadModem logbook": "MadModem-Logbuch drucken", "Save logbook PDF": "Logbuch-PDF speichern", "No QSO records to save.": "Keine QSO-Datensätze zum Speichern.", "Logbook file settings": "Logbuch-Dateieinstellungen", "Logbook file": "Logbuchdatei", "Default path": "Standardpfad", "Browse...": "Durchsuchen...", "Use default path": "Standardpfad verwenden", "Cancel": "Abbrechen", "Hamlib available": "Hamlib verfügbar", "Hamlib not compiled in": "Hamlib nicht einkompiliert", "Use CAT PTT for transmit": "CAT PTT zum Senden verwenden", "Radio maker": "Funkgeräte-Hersteller", "Filter models": "Modelle filtern", "Radio model": "Funkgerät-Modell", "CAT serial port": "CAT-Seriellport", "CAT TCP address": "CAT-TCP-Adresse", "Serial speed": "Serielle Geschwindigkeit", "Data bits": "Datenbits", "Stop bits": "Stoppbits", "None": "Keine", "Unchanged": "Unverändert", "None / audio only": "Keine / nur Audio", "Serial RTS": "Seriell RTS", "Serial DTR": "Seriell DTR", "Poll interval": "Polling-Intervall", "Test CAT": "CAT testen", "Test TX": "TX testen", "Force RX": "RX erzwingen", "Runtime log": "Laufzeitprotokoll", "Ready": "Bereit", "Clear": "Löschen", "FT activity": "FT-Aktivität", "FT decoder": "FT-Decoder", "Station identity required": "Stationsidentität erforderlich"
    },
    "no": {
        "MadModem logbook": "MadModem QSO-logg", "Advanced search": "Avansert søk", "From UTC": "Fra UTC", "To UTC": "Til UTC", "Clear search": "Tøm søk", "Any": "Alle", "Callsign": "Kallesignal", "RST sent": "RST sendt", "RST rcvd": "RST mottatt", "Import ADIF...": "Importer ADIF...", "Export all...": "Eksporter alt...", "Export result...": "Eksporter resultat...", "Export selected...": "Eksporter valgte...", "Delete selected": "Slett valgte", "Print...": "Skriv ut...", "Save PDF...": "Lagre PDF...", "Close": "Lukk", "Import failed:": "Import mislyktes:", "Imported %1 QSO records.": "Importerte %1 QSO-poster.", "No QSO records to export.": "Ingen QSO-poster å eksportere.", "Export failed:": "Eksport mislyktes:", "Delete selected QSOs": "Slett valgte QSO-er", "Select one or more QSO records to delete.": "Velg én eller flere QSO-poster som skal slettes.", "Delete failed:": "Sletting mislyktes:", "No matching QSO records were removed.": "Ingen samsvarende QSO-poster ble fjernet.", "Deleted %1 QSO record(s).": "Slettet %1 QSO-post(er).", "Print logbook": "Skriv ut logg", "No QSO records to print.": "Ingen QSO-poster å skrive ut.", "Logbook file settings": "Innstillinger for loggfil", "Logbook file": "Loggfil", "Default path": "Standardsti", "Browse...": "Bla gjennom...", "Use default path": "Bruk standardsti", "Cancel": "Avbryt", "Runtime log": "Kjøretidslogg", "Ready": "Klar", "Clear": "Tøm", "FT activity": "FT-aktivitet", "FT decoder": "FT-dekoder"
    },
    "cs": {
        "MadModem logbook": "QSO deník MadModem", "Advanced search": "Rozšířené hledání", "From UTC": "Od UTC", "To UTC": "Do UTC", "Clear search": "Vymazat hledání", "Any": "Libovolné", "Callsign": "Značka", "RST sent": "RST odesláno", "RST rcvd": "RST přijato", "Import ADIF...": "Importovat ADIF...", "Export all...": "Exportovat vše...", "Export result...": "Exportovat výsledek...", "Export selected...": "Exportovat vybrané...", "Delete selected": "Smazat vybrané", "Print...": "Tisk...", "Save PDF...": "Uložit PDF...", "Close": "Zavřít", "Import failed:": "Import selhal:", "Imported %1 QSO records.": "Importováno %1 QSO záznamů.", "No QSO records to export.": "Žádné QSO záznamy k exportu.", "Export failed:": "Export selhal:", "Delete selected QSOs": "Smazat vybraná QSO", "Select one or more QSO records to delete.": "Vyber jeden nebo více QSO záznamů ke smazání.", "Delete failed:": "Smazání selhalo:", "No matching QSO records were removed.": "Nebyly odstraněny žádné odpovídající QSO záznamy.", "Deleted %1 QSO record(s).": "Smazáno %1 QSO záznamů.", "Print logbook": "Tisk QSO deníku", "No QSO records to print.": "Žádné QSO záznamy k tisku.", "Logbook file settings": "Nastavení souboru QSO deníku", "Logbook file": "Soubor deníku", "Default path": "Výchozí cesta", "Browse...": "Procházet...", "Use default path": "Použít výchozí cestu", "Cancel": "Zrušit", "Runtime log": "Běhový log", "Ready": "Připraveno", "Clear": "Vymazat", "FT activity": "FT aktivita", "FT decoder": "FT dekodér"
    },
}

def translate_value(lang: str, english: str) -> str:
    if lang == "en":
        return english
    if english in EXACT.get(lang, {}):
        return EXACT[lang][english]
    if english in COMMON_EXACT.get(lang, {}):
        return COMMON_EXACT[lang][english]
    if english in EXACT["it"] and lang == "it":
        return EXACT["it"][english]
    # Preserve pure technical/numeric/callsign/stylesheet-ish strings.
    if TECH_RE.match(english) or "{" in english or "}" in english or "background-color:" in english:
        return english
    out = english
    # Common phrases that may appear inside longer status/log messages.
    phrase_overrides = {
        "it": [("Logbook", "Registro QSO"), ("Soundcard", "Scheda audio"), ("sound-card", "scheda audio"), ("Waterfall", "Waterfall"), ("waterfall", "waterfall"), ("callsign", "nominativo"), ("Callsign", "Nominativo"), ("locator", "locator"), ("Grid", "Locator"), ("grid", "locator"), ("received", "ricevuto"), ("Received", "Ricevuto"), ("decoded", "decodificato"), ("Decoded", "Decodificato"), ("completed", "completato"), ("Completed", "Completato")],
        "fr": [("Logbook", "Journal QSO"), ("Soundcard", "Carte son"), ("sound-card", "carte son"), ("callsign", "indicatif"), ("Callsign", "Indicatif"), ("Grid", "Locator"), ("grid", "locator"), ("received", "reçu"), ("Received", "Reçu"), ("decoded", "décodé"), ("Decoded", "Décodé")],
        "de": [("Logbook", "QSO-Logbuch"), ("Soundcard", "Soundkarte"), ("sound-card", "Soundkarte"), ("callsign", "Rufzeichen"), ("Callsign", "Rufzeichen"), ("Grid", "Locator"), ("grid", "Locator"), ("received", "empfangen"), ("Received", "Empfangen"), ("decoded", "dekodiert"), ("Decoded", "Dekodiert")],
        "no": [("Logbook", "QSO-logg"), ("Soundcard", "Lydkort"), ("sound-card", "lydkort"), ("callsign", "kallesignal"), ("Callsign", "Kallesignal"), ("Grid", "Lokator"), ("grid", "lokator"), ("received", "mottatt"), ("Received", "Mottatt"), ("decoded", "dekodet"), ("Decoded", "Dekodet")],
        "cs": [("Logbook", "QSO deník"), ("Soundcard", "Zvuková karta"), ("sound-card", "zvuková karta"), ("callsign", "značka"), ("Callsign", "Značka"), ("Grid", "Locator"), ("grid", "locator"), ("received", "přijato"), ("Received", "Přijato"), ("decoded", "dekódováno"), ("Decoded", "Dekódováno")],
    }
    for a, b in phrase_overrides.get(lang, []):
        out = out.replace(a, b)
    for a, b in TERMS.get(lang, []):
        out = re.sub(rf"\b{re.escape(a)}\b", b, out)
    return out


KEY_EXACT: dict[str, dict[str, str]] = {
    "it": {
        "ft8_deep_decode": "Deep decode / 3 passaggi",
        "ft8_deep_decode_tooltip": "Seleziona il percorso MSHV a tre passaggi con sottrazione e nuova scansione. È mutuamente esclusivo con DSP++ / 4 passaggi e usa più CPU del single-pass.",
        "ft8_dsp_plus_decode": "DSP++ / 4 passaggi",
        "ft8_dsp_plus_decode_tooltip": "Seleziona il percorso DSP++ MSHV-style a quattro passaggi con sottrazione e nuova scansione. È mutuamente esclusivo con Deep decode / 3 passaggi.",
        "ft_analyze_wav": "Analizza WAV FT...",
        "ft_analyze_wav_tooltip": "Carica un file WAV FT8/FT4 registrato e decodificalo offline con lo stesso worker FT isolato. Non attiva mai il PTT né lo scheduler TX.",
        "ft8_decode_performance_value_single": "MSHV-derived, single-pass",
        "ft8_decode_performance_value_deep": "MSHV-derived, deep / 3 passaggi",
        "ft8_decode_performance_value_dsp_plus": "MSHV-derived, DSP++ / 4 passaggi",
    },
    "fr": {
        "ft8_deep_decode": "Décodage profond / 3 passes",
        "ft8_deep_decode_tooltip": "Sélectionne le chemin MSHV à trois passes avec soustraction et nouveau balayage. Mutuellement exclusif avec DSP++ / 4 passes et plus coûteux que le single-pass.",
        "ft8_dsp_plus_decode": "DSP++ / 4 passes",
        "ft8_dsp_plus_decode_tooltip": "Sélectionne le chemin DSP++ de style MSHV à quatre passes avec soustraction et nouveau balayage. Mutuellement exclusif avec le décodage profond / 3 passes.",
        "ft_analyze_wav": "Analyser WAV FT...",
        "ft_analyze_wav_tooltip": "Charge un fichier WAV FT8/FT4 enregistré et le décode hors ligne avec le même worker FT isolé. Ne déclenche jamais le PTT ni le planificateur TX.",
    },
    "de": {
        "ft8_deep_decode": "Deep Decode / 3 Durchläufe",
        "ft8_deep_decode_tooltip": "Wählt den MSHV-artigen Drei-Durchlauf-Pfad mit Subtraktion und erneutem Scan. Gegenseitig exklusiv mit DSP++ / 4 Durchläufe und CPU-intensiver als Single-Pass.",
        "ft8_dsp_plus_decode": "DSP++ / 4 Durchläufe",
        "ft8_dsp_plus_decode_tooltip": "Wählt den MSHV-artigen DSP++-Pfad mit vier Durchläufen, Subtraktion und erneutem Scan. Gegenseitig exklusiv mit Deep Decode / 3 Durchläufe.",
        "ft_analyze_wav": "FT-WAV analysieren...",
        "ft_analyze_wav_tooltip": "Lädt eine aufgezeichnete FT8/FT4-WAV-Datei und dekodiert sie offline im isolierten FT-Worker. PTT und TX-Scheduler werden nie aktiviert.",
    },
    "no": {
        "ft8_deep_decode": "Dypdekoding / 3 pass",
        "ft8_deep_decode_tooltip": "Velger MSHV-stil med tre pass, subtraksjon og ny skanning. Gjensidig utelukkende med DSP++ / 4 pass og bruker mer CPU enn single-pass.",
        "ft8_dsp_plus_decode": "DSP++ / 4 pass",
        "ft8_dsp_plus_decode_tooltip": "Velger DSP++ i MSHV-stil med fire pass, subtraksjon og ny skanning. Gjensidig utelukkende med dypdekoding / 3 pass.",
        "ft_analyze_wav": "Analyser FT WAV...",
        "ft_analyze_wav_tooltip": "Laster en opptatt FT8/FT4 WAV-fil og dekoder den offline med samme isolerte FT-worker. Starter aldri PTT eller TX-planlegger.",
    },
    "cs": {
        "ft8_deep_decode": "Hluboké dekódování / 3 průchody",
        "ft8_deep_decode_tooltip": "Vybere cestu ve stylu MSHV se třemi průchody, odečtením a novým skenováním. Vzájemně se vylučuje s DSP++ / 4 průchody a používá více CPU než single-pass.",
        "ft8_dsp_plus_decode": "DSP++ / 4 průchody",
        "ft8_dsp_plus_decode_tooltip": "Vybere cestu DSP++ ve stylu MSHV se čtyřmi průchody, odečtením a novým skenováním. Vzájemně se vylučuje s hlubokým dekódováním / 3 průchody.",
        "ft_analyze_wav": "Analyzovat FT WAV...",
        "ft_analyze_wav_tooltip": "Načte zaznamenaný FT8/FT4 WAV soubor a dekóduje jej offline stejným izolovaným FT workerem. Nikdy nespíná PTT ani TX scheduler.",
    },
}

def main() -> int:
    canonical = harvest_keys()
    TRANS_DIR.mkdir(exist_ok=True)

    # Keep stable-ish ordering: explicit action/menu keys first if present,
    # otherwise insertion order from existing en + harvested additions.
    for lang in LANGS:
        existing = read_ini(TRANS_DIR / f"ui_{lang}.ini")
        data: OrderedDict[str, str] = OrderedDict()
        for k, english in canonical.items():
            exact = KEY_EXACT.get(lang, {}).get(k)
            if exact is not None:
                data[k] = exact
            elif k in existing and existing[k].strip():
                # Preserve manually curated translations, especially the
                # ADIFMaster-style logbook strings added after harvesting.
                data[k] = existing[k]
            else:
                data[k] = translate_value(lang, english)
        write_ini(TRANS_DIR / f"ui_{lang}.ini", lang, data)
        print(f"{lang}: {len(data)} keys")
    return 0

if __name__ == "__main__":
    sys.exit(main())
